import { Campaign, DailyProgress, ActivityUpdate } from './types';

// Extended Mock Data for all features
import type { CampaignSubmission } from './types';

// ============ RBAC - CLIENTS & TEAM ============
export interface ClientData {
  id: string;
  name: string;
  industry: string;
  campaignManager: string;
  backupManager: string;
  campaignStatus: 'Active' | 'Paused' | 'Completed';
  leadsUploaded: number;
  lastActivity: string;
  activeCampaigns: number;
}

export const mockClients: ClientData[] = [
  {
    id: 'client_1',
    name: 'Intentsify',
    industry: 'Information Technology',
    campaignManager: 'Anish Akkoat',
    backupManager: 'Arjun Patel',
    campaignStatus: 'Active',
    leadsUploaded: 1594,
    lastActivity: '2 hours ago',
    activeCampaigns: 2,
  },
  {
    id: 'client_2',
    name: 'TechCo Ltd',
    industry: 'SaaS',
    campaignManager: 'Anish Akkoat',
    backupManager: 'Arjun Patel',
    campaignStatus: 'Active',
    leadsUploaded: 2108,
    lastActivity: '1 day ago',
    activeCampaigns: 2,
  },
  {
    id: 'client_3',
    name: 'Meridian Group',
    industry: 'Financial Services',
    campaignManager: 'Anish Akkoat',
    backupManager: 'Arjun Patel',
    campaignStatus: 'Active',
    leadsUploaded: 893,
    lastActivity: '3 hours ago',
    activeCampaigns: 2,
  },
  {
    id: 'client_4',
    name: 'Global Innovations Inc',
    industry: 'Manufacturing',
    campaignManager: 'Michael Chen',
    backupManager: 'Emily Rodriguez',
    campaignStatus: 'Active',
    leadsUploaded: 1087,
    lastActivity: '5 hours ago',
    activeCampaigns: 2,
  },
  {
    id: 'client_5',
    name: 'Nexus Enterprises',
    industry: 'Healthcare',
    campaignManager: 'Emily Rodriguez',
    backupManager: 'Michael Chen',
    campaignStatus: 'Active',
    leadsUploaded: 1742,
    lastActivity: '1 day ago',
    activeCampaigns: 2,
  },
];

export interface TeamMember {
  id: string;
  name: string;
  email: string;
  phone: string;
  role: 'Campaign Manager' | 'Campaign Backup' | 'Operations Manager';
  assignedClients: string[];
  activeCampaigns: number;
  clientsAssigned: number;
  status: 'Active' | 'Away';
  avatar?: string;
}

export const mockTeamMembers: TeamMember[] = [
  {
    id: 'tm_1',
    name: 'Anish Akkoat',
    email: 'anish.akkoat@datamaticsbpm.com',
    phone: '+91 22 4040 1234',
    role: 'Campaign Manager',
    assignedClients: ['Intentsify', 'TechCo Ltd', 'Meridian Group'],
    activeCampaigns: 7,
    clientsAssigned: 3,
    status: 'Active',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop',
  },
  {
    id: 'tm_2',
    name: 'Michael Chen',
    email: 'michael.chen@datamaticsbpm.com',
    phone: '+1 415-555-0142',
    role: 'Campaign Manager',
    assignedClients: ['Global Innovations Inc', 'Nexus Enterprises'],
    activeCampaigns: 4,
    clientsAssigned: 2,
    status: 'Active',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop',
  },
  {
    id: 'tm_3',
    name: 'Emily Rodriguez',
    email: 'emily.rodriguez@datamaticsbpm.com',
    phone: '+1 212-555-0198',
    role: 'Campaign Manager',
    assignedClients: ['Nexus Enterprises', 'Global Innovations Inc'],
    activeCampaigns: 3,
    clientsAssigned: 2,
    status: 'Active',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop',
  },
  {
    id: 'tm_4',
    name: 'Arjun Patel',
    email: 'arjun.patel@datamaticsbpm.com',
    phone: '+91 22 4040 5678',
    role: 'Campaign Backup',
    assignedClients: ['Intentsify', 'TechCo Ltd', 'Meridian Group'],
    activeCampaigns: 5,
    clientsAssigned: 3,
    status: 'Active',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop',
  },
  {
    id: 'tm_5',
    name: 'Praful Sanil',
    email: 'praful.sanil@datamaticsbpm.com',
    phone: '+91 22 4040 9012',
    role: 'Operations Manager',
    assignedClients: [],
    activeCampaigns: 14,
    clientsAssigned: 0,
    status: 'Active',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop',
  },
];

// Mock CSV preview data for Lead Upload Modal
export const mockCsvPreview = [
  {
    'First Name': 'Robert',
    'Last Name': 'Chen',
    'Email': 'robert.chen@acmetech.com',
    'Phone': '+1 415-555-1234',
    'Company': 'Acme Technologies Inc.',
    'Job Title': 'Chief Information Security Officer',
    'Source': 'LinkedIn',
  },
  {
    'First Name': 'Jennifer',
    'Last Name': 'Martinez',
    'Email': 'j.martinez@globalfinance.com',
    'Phone': '+1 212-555-5678',
    'Company': 'Global Finance Corp',
    'Job Title': 'IT Director',
    'Source': 'Conference',
  },
  {
    'First Name': 'David',
    'Last Name': 'Kim',
    'Email': 'd.kim@healthcaresolutions.com',
    'Phone': '+1 617-555-9012',
    'Company': 'Healthcare Solutions Ltd',
    'Job Title': 'Security Manager',
    'Source': 'Webinar',
  },
  {
    'First Name': 'Emma',
    'Last Name': 'Thompson',
    'Email': 'e.thompson@londonbanking.co.uk',
    'Phone': '+44 20 7123 4567',
    'Company': 'London Banking Group',
    'Job Title': 'CFO',
    'Source': 'Partner Referral',
  },
  {
    'First Name': 'Michael',
    'Last Name': 'Anderson',
    'Email': 'm.anderson@techsolutions.com',
    'Phone': '+1 555-123-4567',
    'Company': 'Tech Solutions LLC',
    'Job Title': 'VP of Technology',
    'Source': 'Email Campaign',
  },
];

// ============ CAMPAIGNS ============
// 17 campaigns across 5 companies — mixed geographies, types, statuses, pricing, progress
export const mockCampaigns: Campaign[] = [

  // ── Intentsify (Technology) — 5 campaigns ───────────────────────────────────
  {
    id: '1',
    name: 'Enterprise IT Security – US Q2 2026',
    clientCompany: 'Intentsify',
    serviceType: 'Leads',
    status: 'In progress',
    startDate: '2026-04-15',
    endDate: '2026-07-15',
    delivered: 680,
    target: 1000,
    accepted: 605,
    lastUpdated: '2026-05-22',
    geo: 'North America (US, Canada)',
    industry: 'Information Technology, Cybersecurity',
    revenueRange: '$50M – $500M',
    employeeSize: '500 – 5,000',
    jobTitles: 'CIO, CISO, IT Director, Security Manager, VP IT',
    pricingModel: 'Per lead ($45/lead)',
    clientDetails: {
      name: 'Intentsify',
      address: '100 Innovation Drive, San Francisco, CA 94105',
      contact: 'TJ Leyland, tj.leyland@intentsify.com, +1 415-555-0123',
    },
    scopeOfWork: [
      'Generate qualified B2B leads for IT security solutions',
      'Validate all leads through email and phone verification',
      'Ensure leads meet title, company size, and industry criteria',
      'Deliver bi-weekly batches of 150 leads',
    ],
    terms: 'Payment terms: Net 30. Leads replaced if found invalid within 7 days. Campaign pausable with 5 business days notice.',
  },
  {
    id: '2',
    name: 'APAC Cloud Migration Leads – Q2 2026',
    clientCompany: 'Intentsify',
    serviceType: 'Single Touch',
    status: 'In progress',
    startDate: '2026-04-01',
    endDate: '2026-07-31',
    delivered: 374,
    target: 600,
    accepted: 307,
    lastUpdated: '2026-05-21',
    geo: 'Asia Pacific (Singapore, Australia, Japan, India)',
    industry: 'Technology, Cloud Computing, SaaS',
    revenueRange: '$20M – $200M',
    employeeSize: '200 – 2,000',
    jobTitles: 'CTO, VP Engineering, Head of Cloud, DevOps Director',
    pricingModel: 'Per lead ($52/lead)',
    clientDetails: {
      name: 'Intentsify',
      address: '100 Innovation Drive, San Francisco, CA 94105',
      contact: 'TJ Leyland, tj.leyland@intentsify.com, +1 415-555-0123',
    },
    scopeOfWork: [
      'Identify cloud migration decision-makers across APAC',
      'Single touch email outreach with asset download tracking',
      'Capture opt-in consent per APAC privacy regulations',
      'Bi-monthly batch delivery of 125 leads',
    ],
    terms: 'Payment terms: Net 30. APAC PDPA/GDPR compliance required on all leads.',
  },
  {
    id: '1c',
    name: 'AI-Powered SaaS Lead Generation Q2 2026',
    clientCompany: 'Intentsify',
    serviceType: 'Leads',
    status: 'Pending Approval',
    startDate: '2026-05-01',
    endDate: '2026-07-31',
    delivered: 0,
    target: 400,
    accepted: 0,
    lastUpdated: '2026-05-21',
    geo: 'North America (California, New York, Texas, Illinois, Washington)',
    industry: 'Software / SaaS',
    revenueRange: 'Series B+',
    employeeSize: '500 – 5,000',
    jobTitles: 'CTO, VP Engineering, Director of AI, Head of Data Science, VP Product',
    pricingModel: 'Per lead ($55/lead)',
    clientDetails: {
      name: 'Intentsify',
      address: '100 Innovation Drive, San Francisco, CA 94105',
      contact: 'TJ Leyland, tj.leyland@intentsify.com, +1 415-555-0123',
    },
    scopeOfWork: [
      'Generate qualified leads from AI-native companies (Series B+)',
      'Focus on companies actively deploying AI infrastructure in production',
      'Batch delivery of 100 leads per month',
      'Bi-weekly check-in calls with campaign manager',
    ],
    terms: 'Campaign pending approval by campaign manager. Job card to be issued upon approval.',
  },
  {
    id: '1d',
    name: 'Healthcare IT Director Content Syndication',
    clientCompany: 'Intentsify',
    serviceType: 'Content Syndication',
    status: 'Changes Requested',
    startDate: '2026-04-01',
    endDate: '2026-06-30',
    delivered: 0,
    target: 300,
    accepted: 0,
    lastUpdated: '2026-05-19',
    geo: 'United States',
    industry: 'Healthcare / Medical Devices',
    revenueRange: '$50M+',
    employeeSize: '200 – 5,000',
    jobTitles: 'CIO, IT Director, VP Healthcare IT, Director of Clinical Informatics',
    pricingModel: 'Per download ($38/download)',
    clientDetails: {
      name: 'Intentsify',
      address: '100 Innovation Drive, San Francisco, CA 94105',
      contact: 'TJ Leyland, tj.leyland@intentsify.com, +1 415-555-0123',
    },
    scopeOfWork: [
      'Distribute Q1 Healthcare AI white paper to target audience',
      'HIPAA-compliant contacts only',
      'Verified opt-in download tracking throughout',
      'CRM-ready lead file delivered upon completion',
    ],
    terms: 'Changes requested by campaign manager — awaiting revised CPL/volume confirmation from client.',
  },
  {
    id: '3',
    name: 'Cybersecurity Awareness Campaign – Q4 2025',
    clientCompany: 'Intentsify',
    serviceType: 'Content Syndication',
    status: 'Completed',
    startDate: '2025-10-01',
    endDate: '2025-12-31',
    delivered: 540,
    target: 500,
    accepted: 491,
    lastUpdated: '2025-12-31',
    geo: 'United States',
    industry: 'Information Technology, Financial Services, Healthcare',
    revenueRange: '$50M+',
    employeeSize: '500+',
    jobTitles: 'CISO, CIO, IT Director, Security Architect',
    pricingModel: 'Per download ($38/download)',
    clientDetails: {
      name: 'Intentsify',
      address: '100 Innovation Drive, San Francisco, CA 94105',
      contact: 'TJ Leyland, tj.leyland@intentsify.com, +1 415-555-0123',
    },
    scopeOfWork: [
      'Distribute 2025 State of Cybersecurity whitepaper',
      'Drive downloads from decision-maker audience',
      'Provide verified contact data with each download',
      'Monthly reporting dashboard access provided',
    ],
    terms: 'Payment terms: Net 30. Overage at standard $38 CPL. Final report within 5 business days of completion.',
  },
  {
    id: 'camp_1e',
    name: 'Enterprise Cyber Threat Intelligence – US Q2 2026',
    clientCompany: 'Intentsify',
    serviceType: 'Leads',
    status: 'In progress',
    startDate: '2026-05-01',
    endDate: '2026-08-31',
    delivered: 200,
    target: 500,
    accepted: 184,
    lastUpdated: '2026-05-22',
    geo: 'United States',
    industry: 'Technology, Cybersecurity',
    revenueRange: '$50M – $1B',
    employeeSize: '1,000 – 10,000',
    jobTitles: 'CISO, Director of Threat Intelligence, Security Operations Lead',
    pricingModel: 'Per lead ($65/lead)',
    clientDetails: {
      name: 'Intentsify',
      address: '100 Innovation Drive, San Francisco, CA 94105',
      contact: 'TJ Leyland, tj.leyland@intentsify.com, +1 415-555-0123',
    },
    scopeOfWork: [
      'Generate qualified leads for cyber threat intelligence solutions',
      'Validate contact emails and direct phone numbers',
      'Target companies with active cybersecurity initiatives',
      'Deliver weekly batches of 100 leads',
    ],
    terms: 'Payment terms: Net 30. Standard CPL is $65. Lead replacement for invalid emails.',
  },

  // ── TechCo Ltd (SaaS) — 4 campaigns ────────────────────────────────────────
  {
    id: '4',
    name: 'Enterprise Outreach – North America Q2 2026',
    clientCompany: 'TechCo Ltd',
    serviceType: 'Double Touch',
    status: 'In progress',
    startDate: '2026-04-08',
    endDate: '2026-07-15',
    delivered: 1203,
    target: 1500,
    accepted: 915,
    lastUpdated: '2026-05-22',
    geo: 'North America (US)',
    industry: 'Software, SaaS, Cloud',
    revenueRange: '$10M – $200M',
    employeeSize: '100 – 2,000',
    jobTitles: 'VP Sales, VP Marketing, Director of Revenue, CRO',
    pricingModel: 'Per lead ($42/lead)',
    clientDetails: {
      name: 'TechCo Ltd',
      address: '250 Tech Boulevard, Austin, TX 78701',
      contact: 'James Whitfield, j.whitfield@techcoltd.com, +1 512-555-0800',
    },
    scopeOfWork: [
      'Two-touch email sequence targeting SaaS revenue leaders',
      'Personalised subject lines using company and title data',
      'Weekly batch delivery of 300 contacts per cycle',
      'Monthly optimisation review call included',
    ],
    terms: 'Payment terms: Net 30. Double-touch sequence must complete before lead is counted.',
  },
  {
    id: '5',
    name: 'SMB SaaS Decision Makers – EMEA 2025–26',
    clientCompany: 'TechCo Ltd',
    serviceType: 'Leads',
    status: 'Completed',
    startDate: '2025-11-01',
    endDate: '2026-02-28',
    delivered: 905,
    target: 800,
    accepted: 624,
    lastUpdated: '2026-02-28',
    geo: 'EMEA (UK, Germany, Netherlands, France, Sweden)',
    industry: 'Software, E-commerce, Professional Services',
    revenueRange: '$5M – $100M',
    employeeSize: '50 – 1,000',
    jobTitles: 'CEO, COO, Head of Operations, IT Manager, Procurement Manager',
    pricingModel: 'Per lead ($38/lead)',
    clientDetails: {
      name: 'TechCo Ltd',
      address: '250 Tech Boulevard, Austin, TX 78701',
      contact: 'James Whitfield, j.whitfield@techcoltd.com, +1 512-555-0800',
    },
    scopeOfWork: [
      'Generate GDPR-compliant SMB leads across 5 EMEA markets',
      'Localised outreach in English, German, French where required',
      'Quarterly batch delivery schedule with suppression applied',
      'Client suppression list applied before each delivery',
    ],
    terms: 'Payment terms: Net 30. GDPR-compliant opt-in required on every lead. Overage at $38 CPL.',
  },
  {
    id: '6',
    name: 'APAC SaaS Appointment Setting – Q2 2026',
    clientCompany: 'TechCo Ltd',
    serviceType: 'Appointment Setting',
    status: 'In progress',
    startDate: '2026-04-01',
    endDate: '2026-06-30',
    delivered: 80,
    target: 80,
    accepted: 68,
    lastUpdated: '2026-05-20',
    geo: 'Asia Pacific (Singapore, Australia, Japan)',
    industry: 'Technology, SaaS, Cloud Infrastructure',
    revenueRange: '$20M – $500M',
    employeeSize: '200 – 5,000',
    jobTitles: 'CTO, VP Product, Head of Engineering, Director of IT',
    pricingModel: 'Per appointment ($220/appointment)',
    clientDetails: {
      name: 'TechCo Ltd',
      address: '250 Tech Boulevard, Austin, TX 78701',
      contact: 'James Whitfield, j.whitfield@techcoltd.com, +1 512-555-0800',
    },
    scopeOfWork: [
      'Set qualified discovery calls with APAC technology leaders',
      'Confirm each appointment 48 hours in advance',
      'Provide 1-page prospect brief before each meeting',
      'Reschedule no-shows free of charge within campaign window',
    ],
    terms: 'Payment terms: Net 30. Campaign kickoff scheduled Apr 1, 2026. Job card awaiting final signature.',
  },
  {
    id: '6b',
    name: 'EMEA Financial Services BANT – Q2 2026',
    clientCompany: 'TechCo Ltd',
    serviceType: 'BANT',
    status: 'Pending Approval',
    startDate: '2026-05-01',
    endDate: '2026-07-31',
    delivered: 0,
    target: 150,
    accepted: 0,
    lastUpdated: '2026-05-20',
    geo: 'EMEA (UK, Germany, France, Netherlands, Sweden)',
    industry: 'Financial Services, Banking',
    revenueRange: '$500M+',
    employeeSize: '1,000+',
    jobTitles: 'CFO, Head of Finance, VP Financial Operations, Chief Risk Officer',
    pricingModel: 'Per qualified lead ($120/lead)',
    clientDetails: {
      name: 'TechCo Ltd',
      address: '250 Tech Boulevard, Austin, TX 78701',
      contact: 'James Whitfield, j.whitfield@techcoltd.com, +1 512-555-0800',
    },
    scopeOfWork: [
      'BANT-qualify financial services leaders across 5 EMEA markets',
      'Confirm budget authority and purchase timeline on every lead',
      'English, German, French phone interviews as required',
      'Deliver qualification notes with each accepted lead',
    ],
    terms: 'Campaign pending approval by campaign manager. Projected launch May 2026.',
  },
  {
    id: 'camp_2d',
    name: 'Enterprise HR SaaS Pilot – North America 2026',
    clientCompany: 'TechCo Ltd',
    serviceType: 'Leads',
    status: 'In progress',
    startDate: '2026-05-01',
    endDate: '2026-08-31',
    delivered: 150,
    target: 300,
    accepted: 120,
    lastUpdated: '2026-05-22',
    geo: 'North America (US, Canada)',
    industry: 'Software, SaaS, HR Tech',
    revenueRange: '$30M – $500M',
    employeeSize: '500 – 5,000',
    jobTitles: 'CHRO, VP Human Resources, Director of Talent Management',
    pricingModel: 'Per lead ($48/lead)',
    clientDetails: {
      name: 'TechCo Ltd',
      address: '250 Tech Boulevard, Austin, TX 78701',
      contact: 'James Whitfield, j.whitfield@techcoltd.com, +1 512-555-0800',
    },
    scopeOfWork: [
      'Generate leads for enterprise HR SaaS pilot programs',
      'Focus on companies expanding remote/hybrid operations',
      'Weekly lead delivery of 75 leads',
    ],
    terms: 'Payment terms: Net 30. Overage allowed up to 10% above target.',
  },

  // ── Meridian Group (Financial Services) — 4 campaigns ─────────────────────
  {
    id: '7',
    name: 'UK Banking Sector BANT Qualification – Q1 2026',
    clientCompany: 'Meridian Group',
    serviceType: 'BANT',
    status: 'In progress',
    startDate: '2026-04-01',
    endDate: '2026-07-31',
    delivered: 412,
    target: 500,
    accepted: 305,
    lastUpdated: '2026-05-11',
    geo: 'EMEA (United Kingdom)',
    industry: 'Banking, Financial Services',
    revenueRange: '$250M+',
    employeeSize: '1,000+',
    jobTitles: 'CFO, Head of Digital Banking, Innovation Director, CRO',
    pricingModel: 'Per qualified lead ($125/lead)',
    clientDetails: {
      name: 'Meridian Group',
      address: '14 Canary Wharf, London, UK E14 5AB',
      contact: 'David Okafor, d.okafor@meridiangroup.co.uk, +44 20 7946 0123',
    },
    scopeOfWork: [
      'Qualify leads through BANT framework (Budget, Authority, Need, Timeline)',
      'Phone interviews to confirm all 4 BANT criteria',
      'Document qualification notes and pain points per lead',
      'Deliver only fully qualified opportunities in fortnightly batches',
    ],
    terms: 'Payment terms: Net 45. All 4 BANT criteria must be confirmed. Sample review required before bulk delivery.',
  },
  {
    id: '8',
    name: 'FinTech Decision Makers – DACH Region',
    clientCompany: 'Meridian Group',
    serviceType: 'Leads',
    status: 'Paused',
    startDate: '2026-01-15',
    endDate: '2026-04-30',
    delivered: 245,
    target: 400,
    accepted: 162,
    lastUpdated: '2026-02-10',
    geo: 'EMEA (Germany, Austria, Switzerland)',
    industry: 'Financial Technology, Insurance, Wealth Management',
    revenueRange: '$100M – $1B',
    employeeSize: '500 – 5,000',
    jobTitles: 'CTO, CDO, VP Digital Transformation, Head of Payments',
    pricingModel: 'Per lead ($68/lead)',
    clientDetails: {
      name: 'Meridian Group',
      address: '14 Canary Wharf, London, UK E14 5AB',
      contact: 'David Okafor, d.okafor@meridiangroup.co.uk, +44 20 7946 0123',
    },
    scopeOfWork: [
      'German-language outreach to FinTech decision-makers in DACH',
      'Bi-weekly batch delivery of 125 leads per cycle',
      'Translate and localise all contact touchpoints',
      'Apply client suppression list before every batch',
    ],
    terms: 'Payment terms: Net 30. Campaign paused Feb 10 — awaiting revised targeting confirmation from client.',
  },
  {
    id: '9',
    name: 'APAC Appointment Setting – CloudTech Program',
    clientCompany: 'Meridian Group',
    serviceType: 'Appointment Setting',
    status: 'In progress',
    startDate: '2026-03-01',
    endDate: '2026-05-31',
    delivered: 58,
    target: 60,
    accepted: 48,
    lastUpdated: '2026-05-20',
    geo: 'Asia Pacific (Singapore, Australia, India, Japan)',
    industry: 'Technology, Cloud Computing',
    revenueRange: '$50M – $500M',
    employeeSize: '500 – 2,000',
    jobTitles: 'CTO, VP Technology, Head of Cloud Infrastructure, DevOps Director',
    pricingModel: 'Per appointment ($200/appointment)',
    clientDetails: {
      name: 'Meridian Group',
      address: '14 Canary Wharf, London, UK E14 5AB',
      contact: 'David Okafor, d.okafor@meridiangroup.co.uk, +44 20 7946 0123',
    },
    scopeOfWork: [
      'Set confirmed discovery appointments with APAC cloud leaders',
      'Confirm bookings 24 hours in advance of each meeting',
      'Provide detailed prospect brief and tech stack summary',
      'Reschedule no-shows within the same campaign window',
    ],
    terms: 'Payment terms: Net 30. Only attended appointments billed. Briefing notes 1 hour before each call.',
  },
  {
    id: '9b',
    name: 'Nordic FinTech Leads – Single Touch Q2 2026',
    clientCompany: 'Meridian Group',
    serviceType: 'Single Touch',
    status: 'Changes Requested',
    startDate: '2026-05-01',
    endDate: '2026-07-31',
    delivered: 0,
    target: 250,
    accepted: 0,
    lastUpdated: '2026-05-18',
    geo: 'EMEA (Sweden, Norway, Denmark, Finland)',
    industry: 'Financial Technology, Banking, Insurance',
    revenueRange: '$50M – $500M',
    employeeSize: '200 – 2,000',
    jobTitles: 'CTO, Head of Digital Banking, VP Innovation, Director of Payments',
    pricingModel: 'Per lead ($58/lead)',
    clientDetails: {
      name: 'Meridian Group',
      address: '14 Canary Wharf, London, UK E14 5AB',
      contact: 'David Okafor, d.okafor@meridiangroup.co.uk, +44 20 7946 0123',
    },
    scopeOfWork: [
      'Single touch outreach to Nordic FinTech leaders',
      'English and Swedish language outreach versions',
      'GDPR-compliant opt-in on all contacts',
      'Monthly delivery of 85 leads per batch',
    ],
    terms: 'Campaign under review. Changes requested by campaign manager — awaiting client response.',
  },
  {
    id: 'camp_3d',
    name: 'EMEA FinTech Wealth Management – Q2 2026',
    clientCompany: 'Meridian Group',
    serviceType: 'Leads',
    status: 'In progress',
    startDate: '2026-05-01',
    endDate: '2026-08-31',
    delivered: 100,
    target: 200,
    accepted: 88,
    lastUpdated: '2026-05-21',
    geo: 'EMEA (UK, Switzerland, Germany)',
    industry: 'Financial Technology, Wealth Management',
    revenueRange: '$100M+',
    employeeSize: '200 – 2,000',
    jobTitles: 'Head of Wealth Management, CDO Wealth, VP Digital Investments',
    pricingModel: 'Per lead ($75/lead)',
    clientDetails: {
      name: 'Meridian Group',
      address: '14 Canary Wharf, London, UK E14 5AB',
      contact: 'David Okafor, d.okafor@meridiangroup.co.uk, +44 20 7946 0123',
    },
    scopeOfWork: [
      'Generate qualified leads in wealth management tech solutions',
      'Confirm interest in fintech wealth management platforms',
      'Bi-weekly lead delivery of 50 leads',
    ],
    terms: 'Payment terms: Net 45. Leads replaced if found invalid within 14 days.',
  },

  // ── Global Innovations Inc (Manufacturing) — 4 campaigns ───────────────────
  {
    id: '10',
    name: 'Manufacturing Leads – North America Q1 2026',
    clientCompany: 'Global Innovations Inc',
    serviceType: 'Leads',
    status: 'In progress',
    startDate: '2026-01-20',
    endDate: '2026-04-20',
    delivered: 623,
    target: 700,
    accepted: 486,
    lastUpdated: '2026-05-18',
    geo: 'North America (US, Canada)',
    industry: 'Manufacturing, Industrial Automation, Heavy Equipment',
    revenueRange: '$50M – $500M',
    employeeSize: '500 – 5,000',
    jobTitles: 'VP Operations, Plant Manager, Automation Director, Head of Procurement',
    pricingModel: 'Per lead ($55/lead)',
    clientDetails: {
      name: 'Global Innovations Inc',
      address: '2000 Industrial Parkway, Detroit, MI 48201',
      contact: 'Rachel Huang, r.huang@globalinnovations.com, +1 313-555-0400',
    },
    scopeOfWork: [
      'Generate leads for industrial automation solutions across North America',
      'Multi-touch verification of all contacts before delivery',
      'Bi-weekly batch delivery of 175 leads per cycle',
      'Account-based targeting for Fortune 1000 manufacturers',
    ],
    terms: 'Payment terms: Net 30. Leads valid for 30 days from delivery. Replacement within 10 business days.',
  },
  {
    id: '11',
    name: 'EMEA Industrial Automation – Double Touch',
    clientCompany: 'Global Innovations Inc',
    serviceType: 'Double Touch',
    status: 'In progress',
    startDate: '2026-02-15',
    endDate: '2026-05-15',
    delivered: 353,
    target: 500,
    accepted: 285,
    lastUpdated: '2026-05-18',
    geo: 'EMEA (Germany, France, Italy, Spain, Netherlands)',
    industry: 'Manufacturing, Automotive, Aerospace',
    revenueRange: '$100M – $2B',
    employeeSize: '1,000 – 10,000',
    jobTitles: 'VP Manufacturing, Plant Director, Head of Industry 4.0, CTO',
    pricingModel: 'Per lead ($72/lead)',
    clientDetails: {
      name: 'Global Innovations Inc',
      address: '2000 Industrial Parkway, Detroit, MI 48201',
      contact: 'Rachel Huang, r.huang@globalinnovations.com, +1 313-555-0400',
    },
    scopeOfWork: [
      'Two-touch outreach to European manufacturing decision-makers',
      'Localised content for German, French, Italian audiences',
      'Bi-weekly delivery of 125 leads per batch',
      'Industry 4.0 and smart factory vertical focus',
    ],
    terms: 'Payment terms: Net 30. GDPR-compliant data required on all European leads.',
  },
  {
    id: '12',
    name: 'Global Supply Chain Leaders – Content Syndication Q3 2025',
    clientCompany: 'Global Innovations Inc',
    serviceType: 'Content Syndication',
    status: 'Completed',
    startDate: '2025-09-01',
    endDate: '2025-12-15',
    delivered: 780,
    target: 750,
    accepted: 694,
    lastUpdated: '2025-12-15',
    geo: 'Global (US, UK, Germany, Singapore, Australia)',
    industry: 'Manufacturing, Logistics, Supply Chain',
    revenueRange: '$100M+',
    employeeSize: '1,000+',
    jobTitles: 'Chief Supply Chain Officer, VP Logistics, Head of Procurement, COO',
    pricingModel: 'Per download ($42/download)',
    clientDetails: {
      name: 'Global Innovations Inc',
      address: '2000 Industrial Parkway, Detroit, MI 48201',
      contact: 'Rachel Huang, r.huang@globalinnovations.com, +1 313-555-0400',
    },
    scopeOfWork: [
      'Distribute Supply Chain Resilience 2025 industry report',
      'Multi-market distribution across 5 key global regions',
      'Verified opt-in download tracking throughout',
      'CRM-ready lead file delivered monthly with all metadata',
    ],
    terms: 'Payment terms: Net 30. Final delivery completed Dec 15, 2025. Overage billed at $42 CPD.',
  },
  {
    id: '12b',
    name: 'APAC Manufacturing BANT – Q2 2026',
    clientCompany: 'Global Innovations Inc',
    serviceType: 'BANT',
    status: 'Pending Approval',
    startDate: '2026-04-01',
    endDate: '2026-06-30',
    delivered: 0,
    target: 120,
    accepted: 0,
    lastUpdated: '2026-05-18',
    geo: 'Asia Pacific (Japan, South Korea, Singapore, Taiwan)',
    industry: 'Electronics Manufacturing, Semiconductor, Automotive',
    revenueRange: '$200M+',
    employeeSize: '2,000+',
    jobTitles: 'Chief Manufacturing Officer, SVP Operations, Factory Director, Head of Automation',
    pricingModel: 'Per qualified lead ($140/lead)',
    clientDetails: {
      name: 'Global Innovations Inc',
      address: '2000 Industrial Parkway, Detroit, MI 48201',
      contact: 'Rachel Huang, r.huang@globalinnovations.com, +1 313-555-0400',
    },
    scopeOfWork: [
      'BANT-qualify manufacturing decision-makers in East Asia',
      'English and Japanese-language phone interviews',
      'Confirm active budget cycle and purchasing timeline',
      'Deliver fully qualified leads with detailed qualification notes',
    ],
    terms: 'Campaign pending approval. Projected start: Apr 1, 2026. Awaiting campaign manager sign-off.',
  },
  {
    id: 'camp_4c',
    name: 'Smart Factory IoT Integration – US Q2',
    clientCompany: 'Global Innovations Inc',
    serviceType: 'Leads',
    status: 'In progress',
    startDate: '2026-05-01',
    endDate: '2026-08-31',
    delivered: 70,
    target: 150,
    accepted: 57,
    lastUpdated: '2026-05-22',
    geo: 'United States',
    industry: 'Manufacturing, Industrial IoT',
    revenueRange: '$100M+',
    employeeSize: '1,000+',
    jobTitles: 'VP Manufacturing, Smart Factory Director, IoT Integration Lead',
    pricingModel: 'Per lead ($85/lead)',
    clientDetails: {
      name: 'Global Innovations Inc',
      address: '2000 Industrial Parkway, Detroit, MI 48201',
      contact: 'Rachel Huang, r.huang@globalinnovations.com, +1 313-555-0400',
    },
    scopeOfWork: [
      'Generate leads for industrial IoT and smart factory solutions',
      'Focus on operations leaders in large manufacturing plants',
      'Weekly delivery of 35-40 leads',
    ],
    terms: 'Payment terms: Net 30. Overage allowed at standard rate.',
  },

  // ── Nexus Enterprises (Healthcare) — 4 campaigns ───────────────────────────
  {
    id: '13',
    name: 'Healthcare Provider Campaign – Q4 2025',
    clientCompany: 'Nexus Enterprises',
    serviceType: 'Leads',
    status: 'Completed',
    startDate: '2025-10-01',
    endDate: '2025-12-31',
    delivered: 892,
    target: 900,
    accepted: 785,
    lastUpdated: '2025-12-31',
    geo: 'United States',
    industry: 'Healthcare, Hospital Networks, Medical Devices',
    revenueRange: '$100M+',
    employeeSize: '1,000+',
    jobTitles: 'Chief Medical Officer, VP Healthcare IT, Clinical Director, CIO',
    pricingModel: 'Per lead ($60/lead)',
    clientDetails: {
      name: 'Nexus Enterprises',
      address: '88 Health Avenue, Boston, MA 02115',
      contact: 'Dr. Priya Nair, p.nair@nexusenterprise.com, +1 617-555-0900',
    },
    scopeOfWork: [
      'Generate qualified healthcare decision-maker leads',
      'HIPAA-compliant data handling throughout campaign lifecycle',
      'Quarterly batch delivery with full verification',
      '100% replacement guarantee for invalid contacts within 14 days',
    ],
    terms: 'Payment terms: Net 30. HIPAA BAA signed prior to campaign start.',
  },
  {
    id: '14',
    name: 'Medical Device Decision Makers – US 2026',
    clientCompany: 'Nexus Enterprises',
    serviceType: 'Leads',
    status: 'In progress',
    startDate: '2026-01-10',
    endDate: '2026-04-30',
    delivered: 675,
    target: 750,
    accepted: 562,
    lastUpdated: '2026-05-18',
    geo: 'United States',
    industry: 'Medical Devices, MedTech, Diagnostics',
    revenueRange: '$50M – $1B',
    employeeSize: '500 – 10,000',
    jobTitles: 'VP Medical Affairs, Head of Clinical, Director of Regulatory Affairs, CMO',
    pricingModel: 'Per lead ($58/lead)',
    clientDetails: {
      name: 'Nexus Enterprises',
      address: '88 Health Avenue, Boston, MA 02115',
      contact: 'Dr. Priya Nair, p.nair@nexusenterprise.com, +1 617-555-0900',
    },
    scopeOfWork: [
      'Generate MedTech decision-maker leads for diagnostic solutions',
      'HIPAA-compliant contact verification throughout',
      'Bi-weekly delivery of 175 leads per batch',
      'Filter for companies with active procurement cycles only',
    ],
    terms: 'Payment terms: Net 30. HIPAA compliance required. Invalid leads replaced within 10 business days.',
  },
  {
    id: '15',
    name: 'Healthcare IT BANT Qualification – EMEA 2026',
    clientCompany: 'Nexus Enterprises',
    serviceType: 'BANT',
    status: 'In progress',
    startDate: '2026-02-01',
    endDate: '2026-05-31',
    delivered: 270,
    target: 300,
    accepted: 213,
    lastUpdated: '2026-05-18',
    geo: 'EMEA (UK, Germany, Netherlands, France, Nordics)',
    industry: 'Healthcare IT, Digital Health, Hospital Management Systems',
    revenueRange: '$100M+',
    employeeSize: '500+',
    jobTitles: 'CIO, CDO, Head of Digital Health, VP Healthcare Technology',
    pricingModel: 'Per qualified lead ($130/lead)',
    clientDetails: {
      name: 'Nexus Enterprises',
      address: '88 Health Avenue, Boston, MA 02115',
      contact: 'Dr. Priya Nair, p.nair@nexusenterprise.com, +1 617-555-0900',
    },
    scopeOfWork: [
      'BANT-qualify healthcare IT decision-makers across EMEA',
      'Confirm digital health initiative budget and timeline',
      'Phone interviews in English, German, French as required',
      'Deliver detailed qualification notes with each approved lead',
    ],
    terms: 'Payment terms: Net 45. Full BANT required. GDPR consent captured on all European leads.',
  },
  {
    id: '16',
    name: 'APAC MedTech Content Syndication – Q2 2026',
    clientCompany: 'Nexus Enterprises',
    serviceType: 'Content Syndication',
    status: 'Pending Approval',
    startDate: '2026-04-15',
    endDate: '2026-07-15',
    delivered: 0,
    target: 400,
    accepted: 0,
    lastUpdated: '2026-05-18',
    geo: 'Asia Pacific (Japan, Australia, Singapore, South Korea)',
    industry: 'Healthcare, MedTech, Pharmaceuticals',
    revenueRange: '$50M+',
    employeeSize: '500+',
    jobTitles: 'VP Healthcare IT, Head of Digital Medicine, CTO, Clinical Director',
    pricingModel: 'Per download ($45/download)',
    clientDetails: {
      name: 'Nexus Enterprises',
      address: '88 Health Avenue, Boston, MA 02115',
      contact: 'Dr. Priya Nair, p.nair@nexusenterprise.com, +1 617-555-0900',
    },
    scopeOfWork: [
      'Distribute Nexus 2026 APAC Healthcare Technology Report',
      'APAC privacy regulation compliance (PDPA, PIPL, Australian Privacy Act)',
      'Bi-monthly delivery of 200 download leads per batch',
      'English and Japanese localised content versions',
    ],
    terms: 'Campaign pending approval by campaign manager. Job card to be issued upon approval.',
  },
  {
    id: 'camp_5d',
    name: 'Healthcare Telehealth Systems – US Q2',
    clientCompany: 'Nexus Enterprises',
    serviceType: 'Leads',
    status: 'In progress',
    startDate: '2026-05-01',
    endDate: '2026-08-31',
    delivered: 120,
    target: 250,
    accepted: 100,
    lastUpdated: '2026-05-22',
    geo: 'United States',
    industry: 'Healthcare, Telehealth',
    revenueRange: '$50M+',
    employeeSize: '500+',
    jobTitles: 'Chief Telehealth Officer, VP Clinical Operations, Director of Patient Care Tech',
    pricingModel: 'Per lead ($55/lead)',
    clientDetails: {
      name: 'Nexus Enterprises',
      address: '88 Health Avenue, Boston, MA 02115',
      contact: 'Dr. Priya Nair, p.nair@nexusenterprise.com, +1 617-555-0900',
    },
    scopeOfWork: [
      'Generate qualified leads for telehealth system implementations',
      'Focus on clinical operations and patient care technology leaders',
      'Weekly delivery of 60 leads',
    ],
    terms: 'Payment terms: Net 30. HIPAA BAA required.',
  },
];

// ─── Campaign Approval Workflow — Mock Submissions ────────────────────────────
export const mockCampaignSubmissions: CampaignSubmission[] = [
  // ── Pending Approval ────────────────────────────────────────────────────────
  {
    id: 'sub_001',
    campaignName: 'AI-Powered SaaS Lead Generation Q2 2026',
    clientId: 'client_1',
    clientCompany: 'Intentsify',
    submittedBy: 'TJ Leyland',
    submittedAt: '2026-05-20T09:30:00Z',
    assignedManager: 'Anish Akkoat',
    assignedManagerEmail: 'anish.akkoat@datamaticsbpm.com',
    status: 'Pending Approval',
    serviceType: 'Leads',
    geography: 'North America',
    locations: ['California', 'New York', 'Texas', 'Illinois', 'Washington'],
    targetLeads: 400,
    cpl: 55,
    jobTitles: ['CTO', 'VP Engineering', 'Director of AI', 'Head of Data Science', 'VP Product'],
    employeeSize: '500 – 5,000',
    industry: 'Software / SaaS',
    additionalInfo: 'Focus on companies that have raised Series B or later. Prefer leads from companies actively deploying AI infrastructure in production.',
  },
  {
    id: 'sub_002',
    campaignName: 'EMEA Financial Services BANT Q2 2026',
    clientId: 'client_2',
    clientCompany: 'TechCo Ltd',
    submittedBy: 'James Whitfield',
    submittedAt: '2026-05-19T14:45:00Z',
    assignedManager: 'Anish Akkoat',
    assignedManagerEmail: 'anish.akkoat@datamaticsbpm.com',
    status: 'Pending Approval',
    serviceType: 'BANT',
    geography: 'EMEA',
    locations: ['United Kingdom', 'Germany', 'France', 'Netherlands', 'Sweden'],
    targetLeads: 150,
    cpl: 120,
    jobTitles: ['CFO', 'Head of Finance', 'VP Financial Operations', 'Chief Risk Officer'],
    employeeSize: '1,000+',
    industry: 'Financial Services / Banking',
    additionalInfo: 'BANT qualification required on all leads. Budget authority must be confirmed. Purchasing timeline: within 6 months.',
  },
  {
    id: 'sub_005',
    campaignName: 'APAC Manufacturing BANT – Q2 2026',
    clientId: 'client_4',
    clientCompany: 'Global Innovations Inc',
    submittedBy: 'Rachel Huang',
    submittedAt: '2026-05-18T10:15:00Z',
    assignedManager: 'Michael Chen',
    assignedManagerEmail: 'michael.chen@datamaticsbpm.com',
    status: 'Pending Approval',
    serviceType: 'BANT',
    geography: 'APAC',
    locations: ['Japan', 'South Korea', 'Singapore', 'Taiwan'],
    targetLeads: 120,
    cpl: 140,
    jobTitles: ['Chief Manufacturing Officer', 'SVP Operations', 'Factory Director', 'Head of Automation'],
    employeeSize: '2,000+',
    industry: 'Electronics Manufacturing / Semiconductor / Automotive',
    additionalInfo: 'Looking for decision-makers with active capex budgets for manufacturing automation. Japanese-language interviews required for Japan contacts.',
  },
  {
    id: 'sub_006',
    campaignName: 'APAC MedTech Content Syndication – Q2 2026',
    clientId: 'client_5',
    clientCompany: 'Nexus Enterprises',
    submittedBy: 'Dr. Priya Nair',
    submittedAt: '2026-05-21T07:45:00Z',
    assignedManager: 'Emily Rodriguez',
    assignedManagerEmail: 'emily.rodriguez@datamaticsbpm.com',
    status: 'Pending Approval',
    serviceType: 'Content Syndication',
    geography: 'APAC',
    locations: ['Japan', 'Australia', 'Singapore', 'South Korea'],
    targetLeads: 400,
    cpl: 45,
    jobTitles: ['VP Healthcare IT', 'Head of Digital Medicine', 'CTO', 'Clinical Director'],
    employeeSize: '500+',
    industry: 'Healthcare / MedTech / Pharmaceuticals',
    additionalInfo: 'Distribution of our 2026 APAC Healthcare AI report. All contacts must be PDPA/PIPL compliant. Japanese and English versions available.',
  },
  // ── Changes Requested ───────────────────────────────────────────────────────
  {
    id: 'sub_003',
    campaignName: 'Healthcare IT Director Content Syndication',
    clientId: 'client_1',
    clientCompany: 'Intentsify',
    submittedBy: 'TJ Leyland',
    submittedAt: '2026-05-15T11:00:00Z',
    assignedManager: 'Anish Akkoat',
    assignedManagerEmail: 'anish.akkoat@datamaticsbpm.com',
    status: 'Changes Requested',
    serviceType: 'Content Syndication',
    geography: 'North America',
    locations: ['United States'],
    targetLeads: 300,
    cpl: 38,
    jobTitles: ['CIO', 'IT Director', 'VP Healthcare IT', 'Director of Clinical Informatics'],
    employeeSize: '200 – 5,000',
    industry: 'Healthcare / Medical Devices',
    additionalInfo: 'Distribute our Q1 Healthcare AI white paper. Need HIPAA-compliant contacts only.',
    managerNotes: 'The target of 300 leads at $38 CPL is below our capacity threshold for this niche vertical. We can deliver 200 leads at $42 CPL confidently, or 300 at $46 CPL. Please confirm your preference. Also please share the white paper asset so our compliance team can verify content before we begin distribution.',
    reviewedAt: '2026-05-16T09:15:00Z',
    reviewedBy: 'Anish Akkoat',
  },
  {
    id: 'sub_007',
    campaignName: 'Nordic FinTech Leads – Single Touch Q2 2026',
    clientId: 'client_3',
    clientCompany: 'Meridian Group',
    submittedBy: 'David Okafor',
    submittedAt: '2026-05-14T13:30:00Z',
    assignedManager: 'Anish Akkoat',
    assignedManagerEmail: 'anish.akkoat@datamaticsbpm.com',
    status: 'Changes Requested',
    serviceType: 'Single Touch',
    geography: 'EMEA',
    locations: ['Sweden', 'Norway', 'Denmark', 'Finland'],
    targetLeads: 250,
    cpl: 58,
    jobTitles: ['CTO', 'Head of Digital Banking', 'VP Innovation', 'Director of Payments'],
    employeeSize: '200 – 2,000',
    industry: 'Financial Technology / Banking / Insurance',
    additionalInfo: 'Need English and Swedish outreach. All leads must be GDPR opt-in. Focus on challenger banks and digital-first insurers.',
    managerNotes: 'Nordic FinTech is a tight vertical — the 250-lead target at $58 CPL may take 5–6 months at current market capacity. Recommend starting with 150 leads over 3 months to validate quality, then scaling. Also clarify: do you want Swedish-language outreach for all 4 markets, or just Sweden?',
    reviewedAt: '2026-05-15T10:00:00Z',
    reviewedBy: 'Anish Akkoat',
  },
  // ── Approved ────────────────────────────────────────────────────────────────
  {
    id: 'sub_004',
    campaignName: 'APAC CloudTech Appointment Setting Program',
    clientId: 'client_3',
    clientCompany: 'Meridian Group',
    submittedBy: 'David Okafor',
    submittedAt: '2026-05-10T08:00:00Z',
    assignedManager: 'Anish Akkoat',
    assignedManagerEmail: 'anish.akkoat@datamaticsbpm.com',
    status: 'Approved',
    serviceType: 'Appointment Setting',
    geography: 'APAC',
    locations: ['Singapore', 'Australia', 'Japan', 'India'],
    targetLeads: 60,
    cpl: 200,
    jobTitles: ['CTO', 'VP Technology', 'Head of Cloud Infrastructure', 'DevOps Director'],
    employeeSize: '500 – 2,000',
    industry: 'Technology / Cloud Computing',
    reviewedAt: '2026-05-11T10:30:00Z',
    reviewedBy: 'Anish Akkoat',
  },
  {
    id: 'sub_008',
    campaignName: 'North America Enterprise SaaS – Double Touch Q1 2026',
    clientId: 'client_2',
    clientCompany: 'TechCo Ltd',
    submittedBy: 'James Whitfield',
    submittedAt: '2025-12-18T09:00:00Z',
    assignedManager: 'Anish Akkoat',
    assignedManagerEmail: 'anish.akkoat@datamaticsbpm.com',
    status: 'Approved',
    serviceType: 'Double Touch',
    geography: 'North America',
    locations: ['United States'],
    targetLeads: 1500,
    cpl: 42,
    jobTitles: ['VP Sales', 'VP Marketing', 'Director of Revenue', 'CRO', 'Head of Growth'],
    employeeSize: '100 – 2,000',
    industry: 'Software / SaaS / Cloud',
    reviewedAt: '2025-12-20T14:00:00Z',
    reviewedBy: 'Anish Akkoat',
  },
  // ── Declined ────────────────────────────────────────────────────────────────
  {
    id: 'sub_009',
    campaignName: 'Global C-Suite Outreach – Custom Program',
    clientId: 'client_1',
    clientCompany: 'Intentsify',
    submittedBy: 'TJ Leyland',
    submittedAt: '2026-05-01T10:00:00Z',
    assignedManager: 'Anish Akkoat',
    assignedManagerEmail: 'anish.akkoat@datamaticsbpm.com',
    status: 'Declined',
    serviceType: 'Custom',
    geography: 'Global',
    locations: ['United States', 'United Kingdom', 'Germany', 'Singapore', 'Australia', 'Japan'],
    targetLeads: 50,
    cpl: 350,
    jobTitles: ['CEO', 'President', 'Chairman'],
    employeeSize: '5,000+',
    industry: 'All Industries',
    additionalInfo: 'Looking for C-Suite only — CEO/President level. Needs to be warm intros, not cold outreach.',
    managerNotes: 'This campaign profile is outside our current service capability. We do not offer warm introduction programs at the C-Suite/CEO level across 6 global markets. Our existing services cover BANT qualification and appointment setting up to VP level. Recommend scoping a more targeted BANT campaign for SVP/VP decision-makers instead.',
    reviewedAt: '2026-05-02T11:00:00Z',
    reviewedBy: 'Anish Akkoat',
  },
];

export function getPendingSubmissions(): CampaignSubmission[] {
  return mockCampaignSubmissions.filter(s => s.status === 'Pending Approval');
}

export function getSubmissionsNeedingAttention(): CampaignSubmission[] {
  return mockCampaignSubmissions.filter(
    s => s.status === 'Pending Approval' || s.status === 'Changes Requested'
  );
}
// ─────────────────────────────────────────────────────────────────────────────

export const mockDailyProgress: DailyProgress[] = [
  { date: '2026-05-19', leadsSourced: 45, leadsValidated: 38, leadsRejected: 7, bantQualified: 32, appointmentsSet: 2 },
  { date: '2026-05-20', leadsSourced: 52, leadsValidated: 44, leadsRejected: 8, bantQualified: 38, appointmentsSet: 3 },
  { date: '2026-05-21', leadsSourced: 48, leadsValidated: 41, leadsRejected: 7, bantQualified: 35, appointmentsSet: 2 },
  { date: '2026-05-22', leadsSourced: 50, leadsValidated: 43, leadsRejected: 7, bantQualified: 37, appointmentsSet: 3 },
];

export const mockActivityUpdates: ActivityUpdate[] = [
  { title: 'RFP received from client', message: 'RFP received from client', date: '2026-04-05', timestamp: 'Apr 5, 2026', completed: true },
  { title: 'Job card signed by client', message: 'Job card signed by client', date: '2026-04-12', timestamp: 'Apr 12, 2026', completed: true },
  { title: 'Campaign started', message: 'Campaign started — lead generation in progress', date: '2026-04-15', timestamp: 'Apr 15, 2026', completed: true },
  { title: 'First batch delivered (150 leads)', message: 'First batch delivered — 150 leads sent for review', date: '2026-05-04', timestamp: 'May 4, 2026', completed: true },
  { title: 'Second batch delivered (150 leads)', message: 'Second batch delivered — 150 leads sent for review', date: '2026-05-11', timestamp: 'May 11, 2026', completed: true },
  { title: 'Third batch delivered (150 leads)', message: 'Third batch delivered — 150 leads sent for review', date: '2026-05-18', timestamp: 'May 18, 2026', completed: true },
  { title: 'Campaign milestone: 68% complete', message: 'Campaign has reached 68% completion — 680 of 1,000 leads delivered', date: '2026-05-20', timestamp: 'May 20, 2026', completed: true },
  { title: 'Next batch scheduled', message: 'Next delivery scheduled for May 25, 2026 — 150 leads expected', date: '2026-05-25', timestamp: '3 days from now', completed: false },
];

// ============ LEADS ============
export interface Lead {
  id: string;
  campaignId: string;
  campaignName: string;
  firstName: string;
  lastName: string;
  title: string;
  company: string;
  industry: string;
  email: string;
  phone: string;
  country: string;
  employeeSize: string;
  revenue: string;
  leadScore: number;
  status: 'Pending Review' | 'Accepted' | 'Rejected' | 'Contacted';
  deliveryDate: string;
  rejectionReason?: string;
  notes?: string;
}

export const mockLeads: Lead[] = [
  {
    id: 'L001',
    campaignId: '1',
    campaignName: 'Enterprise IT Security Campaign – US Q1 2026',
    firstName: 'Robert',
    lastName: 'Chen',
    title: 'Chief Information Security Officer',
    company: 'Acme Technologies Inc.',
    industry: 'Information Technology',
    email: 'robert.chen@acmetech.com',
    phone: '+1 415-555-1234',
    country: 'United States',
    employeeSize: '1,000 – 2,000',
    revenue: '$250M',
    leadScore: 92,
    status: 'Accepted',
    deliveryDate: '2026-05-18',
  },
  {
    id: 'L002',
    campaignId: '1',
    campaignName: 'Enterprise IT Security Campaign – US Q1 2026',
    firstName: 'Jennifer',
    lastName: 'Martinez',
    title: 'IT Director',
    company: 'Global Finance Corp',
    industry: 'Financial Services',
    email: 'j.martinez@globalfinance.com',
    phone: '+1 212-555-5678',
    country: 'United States',
    employeeSize: '500 – 1,000',
    revenue: '$180M',
    leadScore: 85,
    status: 'Contacted',
    deliveryDate: '2026-05-19',
  },
  {
    id: 'L003',
    campaignId: '1',
    campaignName: 'Enterprise IT Security Campaign – US Q1 2026',
    firstName: 'David',
    lastName: 'Kim',
    title: 'Security Manager',
    company: 'Healthcare Solutions Ltd',
    industry: 'Healthcare',
    email: 'd.kim@healthcaresolutions.com',
    phone: '+1 617-555-9012',
    country: 'United States',
    employeeSize: '200 – 500',
    revenue: '$75M',
    leadScore: 78,
    status: 'Pending Review',
    deliveryDate: '2026-05-21',
  },
  {
    id: 'L004',
    campaignId: '7',
    campaignName: 'UK Banking Sector BANT – Q1 2026',
    firstName: 'Emma',
    lastName: 'Thompson',
    title: 'CFO',
    company: 'London Banking Group',
    industry: 'Banking',
    email: 'e.thompson@londonbanking.co.uk',
    phone: '+44 20 7123 4567',
    country: 'United Kingdom',
    employeeSize: '2,000+',
    revenue: '$850M',
    leadScore: 95,
    status: 'Accepted',
    deliveryDate: '2026-05-18',
  },
  {
    id: 'L005',
    campaignId: '1',
    campaignName: 'Enterprise IT Security Campaign – US Q1 2026',
    firstName: 'Michael',
    lastName: 'Anderson',
    title: 'IT Manager',
    company: 'Small Tech Startup',
    industry: 'Technology',
    email: 'm.anderson@smalltech.com',
    phone: '+1 555-123-4567',
    country: 'United States',
    employeeSize: '50 – 100',
    revenue: '$5M',
    leadScore: 45,
    status: 'Rejected',
    deliveryDate: '2026-05-20',
    rejectionReason: 'Company size below threshold',
  },
  {
    id: 'L006',
    campaignId: '1',
    campaignName: 'Enterprise IT Security Campaign – US Q1 2026',
    firstName: 'Sarah',
    lastName: 'Williams',
    title: 'VP of Information Technology',
    company: 'Enterprise Solutions Group',
    industry: 'Technology',
    email: 's.williams@enterprisesg.com',
    phone: '+1 312-555-2134',
    country: 'United States',
    employeeSize: '1,000 – 2,000',
    revenue: '$320M',
    leadScore: 88,
    status: 'Accepted',
    deliveryDate: '2026-05-19',
  },
  {
    id: 'L007',
    campaignId: '13',
    campaignName: 'Healthcare Provider Campaign – Q4 2025',
    firstName: 'James',
    lastName: 'Patterson',
    title: 'Chief Medical Officer',
    company: 'Regional Hospital Network',
    industry: 'Healthcare',
    email: 'j.patterson@regionalhospital.com',
    phone: '+1 404-555-7890',
    country: 'United States',
    employeeSize: '1,000+',
    revenue: '$450M',
    leadScore: 91,
    status: 'Accepted',
    deliveryDate: '2026-05-11',
  },
  {
    id: 'L008',
    campaignId: '10',
    campaignName: 'Manufacturing Leads – North America Q1 2026',
    firstName: 'Lisa',
    lastName: 'Rodriguez',
    title: 'VP Operations',
    company: 'National Manufacturing Corp',
    industry: 'Manufacturing',
    email: 'l.rodriguez@natmfg.com',
    phone: '+1 214-555-3456',
    country: 'United States',
    employeeSize: '2,000+',
    revenue: '$1.2B',
    leadScore: 94,
    status: 'Accepted',
    deliveryDate: '2026-05-18',
  },
  {
    id: 'L009',
    campaignId: '11',
    campaignName: 'EMEA Industrial Automation – Double Touch',
    firstName: 'Thomas',
    lastName: 'Müller',
    title: 'Head of Industry 4.0',
    company: 'Bavarian Automotive AG',
    industry: 'Automotive',
    email: 't.muller@bavarianautomotive.de',
    phone: '+49 89 555 8901',
    country: 'Germany',
    employeeSize: '5,000 – 10,000',
    revenue: '$2.4B',
    leadScore: 89,
    status: 'Contacted',
    deliveryDate: '2026-05-21',
  },
  {
    id: 'L010',
    campaignId: '7',
    campaignName: 'UK Banking Sector BANT – Q1 2026',
    firstName: 'Sophie',
    lastName: 'Laurent',
    title: 'Head of Digital Banking',
    company: 'Paris Financial Services',
    industry: 'Banking',
    email: 's.laurent@parisfinancial.fr',
    phone: '+33 1 42 55 6789',
    country: 'France',
    employeeSize: '2,000+',
    revenue: '$920M',
    leadScore: 89,
    status: 'Accepted',
    deliveryDate: '2026-05-11',
  },
  {
    id: 'L011',
    campaignId: '2',
    campaignName: 'APAC Cloud Migration Leads – Q1 2026',
    firstName: 'Haruto',
    lastName: 'Tanaka',
    title: 'CTO',
    company: 'Tokyo Cloud Systems KK',
    industry: 'Technology',
    email: 'h.tanaka@tokyocloudsys.co.jp',
    phone: '+81 3 5555 1234',
    country: 'Japan',
    employeeSize: '500 – 1,000',
    revenue: '$210M',
    leadScore: 87,
    status: 'Accepted',
    deliveryDate: '2026-05-19',
  },
  {
    id: 'L012',
    campaignId: '14',
    campaignName: 'Medical Device Decision Makers – US 2026',
    firstName: 'Maria',
    lastName: 'Garcia',
    title: 'VP Medical Affairs',
    company: 'MedTech Innovations',
    industry: 'Healthcare',
    email: 'm.garcia@medtechinno.com',
    phone: '+1 858-555-2345',
    country: 'United States',
    employeeSize: '1,000+',
    revenue: '$380M',
    leadScore: 90,
    status: 'Accepted',
    deliveryDate: '2026-05-18',
  },
  {
    id: 'L013',
    campaignId: '4',
    campaignName: 'Enterprise Outreach – North America Q1 2026',
    firstName: 'William',
    lastName: 'Taylor',
    title: 'VP Sales',
    company: 'CloudFirst Solutions Inc',
    industry: 'SaaS',
    email: 'w.taylor@cloudfirst.com',
    phone: '+1 713-555-6789',
    country: 'United States',
    employeeSize: '200 – 500',
    revenue: '$85M',
    leadScore: 83,
    status: 'Accepted',
    deliveryDate: '2026-05-11',
  },
  {
    id: 'L014',
    campaignId: '15',
    campaignName: 'Healthcare IT BANT Qualification – EMEA 2026',
    firstName: 'Anna',
    lastName: 'Schmidt',
    title: 'Head of Digital Health',
    company: 'Deutsche Kliniken AG',
    industry: 'Healthcare IT',
    email: 'a.schmidt@deutschekliniken.de',
    phone: '+49 69 555 1234',
    country: 'Germany',
    employeeSize: '1,000 – 2,000',
    revenue: '$680M',
    leadScore: 86,
    status: 'Contacted',
    deliveryDate: '2026-05-18',
  },
  {
    id: 'L015',
    campaignId: '4',
    campaignName: 'Enterprise Outreach – North America Q1 2026',
    firstName: 'Christopher',
    lastName: 'Moore',
    title: 'CRO',
    company: 'SaaS Revenue Partners',
    industry: 'Software',
    email: 'c.moore@saasrevenue.com',
    phone: '+1 617-555-3456',
    country: 'United States',
    employeeSize: '500 – 1,000',
    revenue: '$95M',
    leadScore: 91,
    status: 'Accepted',
    deliveryDate: '2026-05-11',
  },
  {
    id: 'L016',
    campaignId: '8',
    campaignName: 'FinTech Decision Makers – DACH Region',
    firstName: 'Olivia',
    lastName: 'Weber',
    title: 'VP Digital Transformation',
    company: 'Swiss FinTech Solutions AG',
    industry: 'Financial Technology',
    email: 'o.weber@swissfintech.ch',
    phone: '+41 44 555 8901',
    country: 'Switzerland',
    employeeSize: '500 – 1,000',
    revenue: '$275M',
    leadScore: 84,
    status: 'Contacted',
    deliveryDate: '2026-05-19',
  },
  {
    id: 'L017',
    campaignId: '10',
    campaignName: 'Manufacturing Leads – North America Q1 2026',
    firstName: 'Kevin',
    lastName: 'Walsh',
    title: 'Plant Manager',
    company: 'Great Lakes Manufacturing',
    industry: 'Manufacturing',
    email: 'k.walsh@greatlakesmfg.com',
    phone: '+1 202-555-4567',
    country: 'United States',
    employeeSize: '1,000 – 2,000',
    revenue: '$340M',
    leadScore: 88,
    status: 'Accepted',
    deliveryDate: '2026-05-11',
  },
  {
    id: 'L018',
    campaignId: '14',
    campaignName: 'Medical Device Decision Makers – US 2026',
    firstName: 'Rachel',
    lastName: 'Cooper',
    title: 'Director of Regulatory Affairs',
    company: 'Health Systems Alliance',
    industry: 'Healthcare',
    email: 'r.cooper@healthsystemsalliance.com',
    phone: '+1 303-555-0678',
    country: 'United States',
    employeeSize: '500+',
    revenue: '$290M',
    leadScore: 79,
    status: 'Pending Review',
    deliveryDate: '2026-05-21',
  },
  {
    id: 'L019',
    campaignId: '2',
    campaignName: 'APAC Cloud Migration Leads – Q1 2026',
    firstName: 'Aisha',
    lastName: 'Krishnamurthy',
    title: 'VP Engineering',
    company: 'Bangalore Cloud Ventures',
    industry: 'Technology',
    email: 'a.krishnamurthy@bangalorecloud.in',
    phone: '+91 80 4040 5678',
    country: 'India',
    employeeSize: '200 – 500',
    revenue: '$45M',
    leadScore: 76,
    status: 'Accepted',
    deliveryDate: '2026-05-22',
  },
  {
    id: 'L020',
    campaignId: '12',
    campaignName: 'Global Supply Chain Leaders – Content Syndication Q3 2025',
    firstName: 'Marcus',
    lastName: 'Jensen',
    title: 'Chief Supply Chain Officer',
    company: 'Scandinavian Logistics Group',
    industry: 'Logistics',
    email: 'm.jensen@scandlogistics.dk',
    phone: '+45 33 55 1234',
    country: 'Denmark',
    employeeSize: '2,000+',
    revenue: '$1.1B',
    leadScore: 93,
    status: 'Accepted',
    deliveryDate: '2025-11-15',
  },
];
