import { Campaign, DailyProgress, ActivityUpdate } from './types';

// Extended Mock Data for all features

// ============ CAMPAIGNS ============
export const mockCampaigns: Campaign[] = [
  {
    id: '1',
    name: 'Enterprise IT Security Campaign Q1 2026',
    clientCompany: 'TechVentures Agency',
    serviceType: 'Leads',
    status: 'In progress',
    startDate: '2026-01-15',
    endDate: '2026-04-15',
    delivered: 320,
    target: 500,
    accepted: 285,
    lastUpdated: '2026-02-25',
    geo: 'North America (US, Canada)',
    industry: 'Information Technology, Cybersecurity',
    revenueRange: '$50M - $500M',
    employeeSize: '500 - 2000',
    jobTitles: 'CIO, CISO, IT Director, Security Manager',
    pricingModel: 'Per lead ($45/lead)',
    clientDetails: {
      name: 'TechVentures Agency',
      address: '123 Market Street, San Francisco, CA 94105',
      contact: 'John Smith, john.smith@techventures.com, +1 415-555-0123'
    },
    scopeOfWork: [
      'Generate qualified B2B leads for IT security solutions',
      'Validate all leads through email and phone verification',
      'Ensure leads meet specified criteria (title, company size, industry)',
      'Deliver leads in batches of 50 every week'
    ],
    terms: 'Payment terms: Net 30. Leads will be replaced if found invalid within 7 days. Campaign can be paused with 5 business days notice.'
  },
  {
    id: '2',
    name: 'Healthcare Content Syndication - Feb 2026',
    clientCompany: 'MedMarketing Solutions',
    serviceType: 'Content Syndication',
    status: 'Completed',
    startDate: '2026-02-01',
    endDate: '2026-02-28',
    delivered: 850,
    target: 800,
    accepted: 820,
    lastUpdated: '2026-02-28',
    geo: 'United States',
    industry: 'Healthcare, Medical Devices',
    revenueRange: '$100M+',
    employeeSize: '1000+',
    jobTitles: 'Chief Medical Officer, VP Healthcare IT, Clinical Director',
    pricingModel: 'Per download ($35/download)',
    clientDetails: {
      name: 'MedMarketing Solutions',
      address: '456 Healthcare Blvd, Boston, MA 02115',
      contact: 'Sarah Johnson, sarah.j@medmarketing.com, +1 617-555-0456'
    },
    scopeOfWork: [
      'Distribute white paper on healthcare IT solutions',
      'Target decision-makers in healthcare organizations',
      'Track downloads and capture contact information',
      'Provide weekly performance reports'
    ],
    terms: 'Payment terms: Net 30. Minimum engagement of 500 downloads. Overage billed at standard rate.'
  },
  {
    id: '3',
    name: 'Financial Services BANT Qualification',
    clientCompany: 'FinTech Growth Partners',
    serviceType: 'BANT',
    status: 'In progress',
    startDate: '2026-01-20',
    endDate: '2026-03-31',
    delivered: 65,
    target: 150,
    accepted: 58,
    lastUpdated: '2026-02-26',
    geo: 'EMEA (UK, Germany, France)',
    industry: 'Financial Services, Banking',
    revenueRange: '$500M+',
    employeeSize: '2000+',
    jobTitles: 'CFO, Head of Digital Banking, Innovation Director',
    pricingModel: 'Per qualified lead ($120/lead)',
    clientDetails: {
      name: 'FinTech Growth Partners',
      address: '789 Finance Way, London, UK EC2N 2DL',
      contact: 'Michael Chen, m.chen@fintechgp.com, +44 20 7123 4567'
    },
    scopeOfWork: [
      'Qualify leads through BANT framework',
      'Conduct phone interviews to verify budget, authority, need, timeline',
      'Document qualification notes for each lead',
      'Deliver only fully qualified opportunities'
    ],
    terms: 'Payment terms: Net 45. BANT criteria must be fully met. Client approval required on sample leads.'
  },
  {
    id: '4',
    name: 'SaaS Appointment Setting - Q1',
    clientCompany: 'CloudScale Ventures',
    serviceType: 'Appointments',
    status: 'Paused',
    startDate: '2026-02-01',
    endDate: '2026-04-30',
    delivered: 18,
    target: 60,
    accepted: 16,
    lastUpdated: '2026-02-20',
    geo: 'North America',
    industry: 'Software, Cloud Computing',
    revenueRange: '$20M - $100M',
    employeeSize: '200 - 1000',
    jobTitles: 'CTO, VP Engineering, DevOps Manager',
    pricingModel: 'Per confirmed appointment ($200/appointment)',
    clientDetails: {
      name: 'CloudScale Ventures',
      address: '321 Tech Plaza, Austin, TX 78701',
      contact: 'Emily Rodriguez, e.rodriguez@cloudscale.com, +1 512-555-0789'
    },
    scopeOfWork: [
      'Set qualified appointments with target decision-makers',
      'Confirm appointments 24 hours in advance',
      'Provide briefing notes on each prospect',
      'Reschedule no-shows at no additional cost'
    ],
    terms: 'Payment terms: Net 30. Appointments must be confirmed and attended. No charge for no-shows if rescheduled.'
  },
  {
    id: '5',
    name: 'Manufacturing Lead Generation Campaign',
    clientCompany: 'Industrial Marketing Group',
    serviceType: 'Leads',
    status: 'Not started',
    startDate: '2026-03-01',
    endDate: '2026-05-31',
    delivered: 0,
    target: 400,
    accepted: 0,
    lastUpdated: '2026-02-27',
    geo: 'Asia Pacific (Japan, Singapore, Australia)',
    industry: 'Manufacturing, Industrial Automation',
    revenueRange: '$100M - $1B',
    employeeSize: '1000 - 5000',
    jobTitles: 'VP Operations, Plant Manager, Automation Director',
    pricingModel: 'Per lead ($55/lead)',
    clientDetails: {
      name: 'Industrial Marketing Group',
      address: '555 Industry Road, Chicago, IL 60601',
      contact: 'David Park, d.park@industrialmktg.com, +1 312-555-0234'
    },
    scopeOfWork: [
      'Generate leads for industrial automation solutions',
      'Target manufacturing decision-makers in APAC region',
      'Validate all leads through multi-touch verification',
      'Deliver bi-weekly batches with full lead data'
    ],
    terms: 'Payment terms: Net 30. Campaign kickoff pending job card signature. Leads guaranteed to meet criteria.'
  },
  {
    id: '6',
    name: 'Retail Technology Appointments Feb-Mar',
    clientCompany: 'RetailTech Aggregators',
    serviceType: 'Appointments',
    status: 'In progress',
    startDate: '2026-02-10',
    endDate: '2026-03-20',
    delivered: 12,
    target: 25,
    accepted: 11,
    lastUpdated: '2026-02-26',
    geo: 'United States',
    industry: 'Retail, E-commerce',
    revenueRange: '$50M+',
    employeeSize: '500+',
    jobTitles: 'CIO, VP Retail Operations, Digital Transformation Lead',
    pricingModel: 'Per confirmed appointment ($180/appointment)',
    clientDetails: {
      name: 'RetailTech Aggregators',
      address: '999 Commerce Drive, Seattle, WA 98101',
      contact: 'Lisa Martinez, l.martinez@retailtech.com, +1 206-555-0567'
    },
    scopeOfWork: [
      'Schedule appointments with retail technology buyers',
      'Qualify prospects before booking',
      'Provide pre-meeting research on each account',
      'Send calendar invites and reminders'
    ],
    terms: 'Payment terms: Net 30. Only attended appointments are billable. Full briefing provided for each meeting.'
  }
];

export const mockDailyProgress: DailyProgress[] = [
  { date: '2026-02-24', leadsSourced: 45, leadsValidated: 38, leadsRejected: 7, bantQualified: 32, appointmentsSet: 2 },
  { date: '2026-02-25', leadsSourced: 52, leadsValidated: 44, leadsRejected: 8, bantQualified: 38, appointmentsSet: 3 },
  { date: '2026-02-26', leadsSourced: 48, leadsValidated: 41, leadsRejected: 7, bantQualified: 35, appointmentsSet: 2 },
  { date: '2026-02-27', leadsSourced: 50, leadsValidated: 43, leadsRejected: 7, bantQualified: 37, appointmentsSet: 3 },
];

export const mockActivityUpdates: ActivityUpdate[] = [
  { title: 'RFP received from client', date: '2026-01-05', completed: true },
  { title: 'Job card signed by client', date: '2026-01-12', completed: true },
  { title: 'Campaign started', date: '2026-01-15', completed: true },
  { title: 'First batch delivered (50 leads)', date: '2026-01-22', completed: true },
  { title: 'Second batch delivered (50 leads)', date: '2026-01-29', completed: true },
  { title: 'Third batch delivered (50 leads)', date: '2026-02-05', completed: true },
  { title: 'Campaign milestone: 50% complete', date: '2026-02-15', completed: true },
  { title: 'Fourth batch delivered (50 leads)', date: '2026-02-20', completed: true },
  { title: 'Fifth batch in progress', date: '2026-02-27', completed: false },
  { title: 'Campaign completion', date: '2026-04-15', completed: false },
];

// ============ LEADS ============
export interface Lead {
  id: string;
  campaignId: string;
  campaignName: string;
  firstName: string;
  lastName: string;
  title: string;
  company: string;
  industry: string;
  email: string;
  phone: string;
  country: string;
  employeeSize: string;
  revenue: string;
  leadScore: number; // 0-100
  status: 'Pending Review' | 'Accepted' | 'Rejected' | 'Contacted';
  deliveryDate: string;
  rejectionReason?: string;
  notes?: string;
}

export const mockLeads: Lead[] = [
  {
    id: 'L001',
    campaignId: '1',
    campaignName: 'Enterprise IT Security Campaign Q1 2026',
    firstName: 'Robert',
    lastName: 'Chen',
    title: 'Chief Information Security Officer',
    company: 'Acme Technologies Inc.',
    industry: 'Information Technology',
    email: 'robert.chen@acmetech.com',
    phone: '+1 415-555-1234',
    country: 'United States',
    employeeSize: '1000-2000',
    revenue: '$250M',
    leadScore: 92,
    status: 'Accepted',
    deliveryDate: '2026-02-20',
  },
  {
    id: 'L002',
    campaignId: '1',
    campaignName: 'Enterprise IT Security Campaign Q1 2026',
    firstName: 'Jennifer',
    lastName: 'Martinez',
    title: 'IT Director',
    company: 'Global Finance Corp',
    industry: 'Financial Services',
    email: 'j.martinez@globalfinance.com',
    phone: '+1 212-555-5678',
    country: 'United States',
    employeeSize: '500-1000',
    revenue: '$180M',
    leadScore: 85,
    status: 'Contacted',
    deliveryDate: '2026-02-21',
  },
  {
    id: 'L003',
    campaignId: '1',
    campaignName: 'Enterprise IT Security Campaign Q1 2026',
    firstName: 'David',
    lastName: 'Kim',
    title: 'Security Manager',
    company: 'Healthcare Solutions Ltd',
    industry: 'Healthcare',
    email: 'd.kim@healthcaresolutions.com',
    phone: '+1 617-555-9012',
    country: 'United States',
    employeeSize: '200-500',
    revenue: '$75M',
    leadScore: 78,
    status: 'Pending Review',
    deliveryDate: '2026-02-25',
  },
  {
    id: 'L004',
    campaignId: '3',
    campaignName: 'Financial Services BANT Qualification',
    firstName: 'Emma',
    lastName: 'Thompson',
    title: 'CFO',
    company: 'London Banking Group',
    industry: 'Banking',
    email: 'e.thompson@londonbanking.co.uk',
    phone: '+44 20 7123 4567',
    country: 'United Kingdom',
    employeeSize: '2000+',
    revenue: '$850M',
    leadScore: 95,
    status: 'Accepted',
    deliveryDate: '2026-02-18',
  },
  {
    id: 'L005',
    campaignId: '1',
    campaignName: 'Enterprise IT Security Campaign Q1 2026',
    firstName: 'Michael',
    lastName: 'Anderson',
    title: 'IT Manager',
    company: 'Small Tech Startup',
    industry: 'Technology',
    email: 'm.anderson@smalltech.com',
    phone: '+1 555-123-4567',
    country: 'United States',
    employeeSize: '50-100',
    revenue: '$5M',
    leadScore: 45,
    status: 'Rejected',
    deliveryDate: '2026-02-22',
    rejectionReason: 'Company size below threshold',
  },
  {
    id: 'L006',
    campaignId: '1',
    campaignName: 'Enterprise IT Security Campaign Q1 2026',
    firstName: 'Sarah',
    lastName: 'Williams',
    title: 'VP of Information Technology',
    company: 'Enterprise Solutions Group',
    industry: 'Technology',
    email: 's.williams@enterprisesg.com',
    phone: '+1 312-555-2134',
    country: 'United States',
    employeeSize: '1000-2000',
    revenue: '$320M',
    leadScore: 88,
    status: 'Accepted',
    deliveryDate: '2026-02-19',
  },
  {
    id: 'L007',
    campaignId: '2',
    campaignName: 'Healthcare Content Syndication - Feb 2026',
    firstName: 'James',
    lastName: 'Patterson',
    title: 'Chief Medical Officer',
    company: 'Regional Hospital Network',
    industry: 'Healthcare',
    email: 'j.patterson@regionalhospital.com',
    phone: '+1 404-555-7890',
    country: 'United States',
    employeeSize: '1000+',
    revenue: '$450M',
    leadScore: 91,
    status: 'Accepted',
    deliveryDate: '2026-02-10',
  },
  {
    id: 'L008',
    campaignId: '1',
    campaignName: 'Enterprise IT Security Campaign Q1 2026',
    firstName: 'Lisa',
    lastName: 'Rodriguez',
    title: 'Director of Cybersecurity',
    company: 'National Retail Chain',
    industry: 'Retail',
    email: 'l.rodriguez@nationalretail.com',
    phone: '+1 214-555-3456',
    country: 'United States',
    employeeSize: '2000+',
    revenue: '$1.2B',
    leadScore: 94,
    status: 'Accepted',
    deliveryDate: '2026-02-17',
  },
  {
    id: 'L009',
    campaignId: '1',
    campaignName: 'Enterprise IT Security Campaign Q1 2026',
    firstName: 'Thomas',
    lastName: 'O\'Brien',
    title: 'IT Security Analyst',
    company: 'Manufacturing Dynamics',
    industry: 'Manufacturing',
    email: 't.obrien@mfgdynamics.com',
    phone: '+1 503-555-8901',
    country: 'United States',
    employeeSize: '500-1000',
    revenue: '$140M',
    leadScore: 72,
    status: 'Contacted',
    deliveryDate: '2026-02-23',
  },
  {
    id: 'L010',
    campaignId: '3',
    campaignName: 'Financial Services BANT Qualification',
    firstName: 'Sophie',
    lastName: 'Laurent',
    title: 'Head of Digital Banking',
    company: 'Paris Financial Services',
    industry: 'Banking',
    email: 's.laurent@parisfinancial.fr',
    phone: '+33 1 42 55 6789',
    country: 'France',
    employeeSize: '2000+',
    revenue: '$920M',
    leadScore: 89,
    status: 'Accepted',
    deliveryDate: '2026-02-15',
  },
  {
    id: 'L011',
    campaignId: '1',
    campaignName: 'Enterprise IT Security Campaign Q1 2026',
    firstName: 'Daniel',
    lastName: 'Foster',
    title: 'Chief Technology Officer',
    company: 'CloudFirst Solutions',
    industry: 'Technology',
    email: 'd.foster@cloudfirst.com',
    phone: '+1 415-555-4321',
    country: 'United States',
    employeeSize: '500-1000',
    revenue: '$210M',
    leadScore: 87,
    status: 'Accepted',
    deliveryDate: '2026-02-16',
  },
  {
    id: 'L012',
    campaignId: '2',
    campaignName: 'Healthcare Content Syndication - Feb 2026',
    firstName: 'Maria',
    lastName: 'Garcia',
    title: 'VP Healthcare IT',
    company: 'MedTech Innovations',
    industry: 'Healthcare',
    email: 'm.garcia@medtechinno.com',
    phone: '+1 858-555-2345',
    country: 'United States',
    employeeSize: '1000+',
    revenue: '$380M',
    leadScore: 90,
    status: 'Accepted',
    deliveryDate: '2026-02-11',
  },
  {
    id: 'L013',
    campaignId: '1',
    campaignName: 'Enterprise IT Security Campaign Q1 2026',
    firstName: 'William',
    lastName: 'Taylor',
    title: 'Security Director',
    company: 'Energy Corp International',
    industry: 'Energy',
    email: 'w.taylor@energycorp.com',
    phone: '+1 713-555-6789',
    country: 'United States',
    employeeSize: '2000+',
    revenue: '$2.1B',
    leadScore: 93,
    status: 'Accepted',
    deliveryDate: '2026-02-14',
  },
  {
    id: 'L014',
    campaignId: '1',
    campaignName: 'Enterprise IT Security Campaign Q1 2026',
    firstName: 'Anna',
    lastName: 'Schmidt',
    title: 'IT Compliance Manager',
    company: 'Deutsche Banking AG',
    industry: 'Banking',
    email: 'a.schmidt@deutschebanking.de',
    phone: '+49 69 555 1234',
    country: 'Germany',
    employeeSize: '1000-2000',
    revenue: '$680M',
    leadScore: 86,
    status: 'Contacted',
    deliveryDate: '2026-02-20',
  },
  {
    id: 'L015',
    campaignId: '1',
    campaignName: 'Enterprise IT Security Campaign Q1 2026',
    firstName: 'Christopher',
    lastName: 'Moore',
    title: 'CIO',
    company: 'Insurance Solutions Ltd',
    industry: 'Insurance',
    email: 'c.moore@insurancesolutions.com',
    phone: '+1 617-555-3456',
    country: 'United States',
    employeeSize: '1000-2000',
    revenue: '$540M',
    leadScore: 91,
    status: 'Accepted',
    deliveryDate: '2026-02-13',
  },
  {
    id: 'L016',
    campaignId: '3',
    campaignName: 'Financial Services BANT Qualification',
    firstName: 'Olivia',
    lastName: 'Brown',
    title: 'Innovation Director',
    company: 'NextGen Finance',
    industry: 'Financial Services',
    email: 'o.brown@nextgenfinance.com',
    phone: '+44 20 7555 8901',
    country: 'United Kingdom',
    employeeSize: '500-1000',
    revenue: '$275M',
    leadScore: 84,
    status: 'Contacted',
    deliveryDate: '2026-02-19',
  },
  {
    id: 'L017',
    campaignId: '1',
    campaignName: 'Enterprise IT Security Campaign Q1 2026',
    firstName: 'Kevin',
    lastName: 'Walsh',
    title: 'Network Security Manager',
    company: 'Telecommunications Inc',
    industry: 'Telecommunications',
    email: 'k.walsh@telecomm.com',
    phone: '+1 202-555-4567',
    country: 'United States',
    employeeSize: '2000+',
    revenue: '$1.8B',
    leadScore: 88,
    status: 'Accepted',
    deliveryDate: '2026-02-12',
  },
  {
    id: 'L018',
    campaignId: '2',
    campaignName: 'Healthcare Content Syndication - Feb 2026',
    firstName: 'Rachel',
    lastName: 'Cooper',
    title: 'Clinical Director',
    company: 'Health Systems Alliance',
    industry: 'Healthcare',
    email: 'r.cooper@healthsystems.com',
    phone: '+1 303-555-7890',
    country: 'United States',
    employeeSize: '1000+',
    revenue: '$410M',
    leadScore: 89,
    status: 'Accepted',
    deliveryDate: '2026-02-09',
  },
  {
    id: 'L019',
    campaignId: '1',
    campaignName: 'Enterprise IT Security Campaign Q1 2026',
    firstName: 'Brian',
    lastName: 'Hughes',
    title: 'Information Security Officer',
    company: 'Pharmaceutical Research Corp',
    industry: 'Pharmaceuticals',
    email: 'b.hughes@pharmresearch.com',
    phone: '+1 609-555-2345',
    country: 'United States',
    employeeSize: '1000-2000',
    revenue: '$890M',
    leadScore: 90,
    status: 'Accepted',
    deliveryDate: '2026-02-18',
  },
  {
    id: 'L020',
    campaignId: '1',
    campaignName: 'Enterprise IT Security Campaign Q1 2026',
    firstName: 'Michelle',
    lastName: 'Lewis',
    title: 'IT Risk Manager',
    company: 'Global Logistics Partners',
    industry: 'Logistics',
    email: 'm.lewis@globallogistics.com',
    phone: '+1 901-555-6789',
    country: 'United States',
    employeeSize: '500-1000',
    revenue: '$190M',
    leadScore: 76,
    status: 'Contacted',
    deliveryDate: '2026-02-22',
  },
  {
    id: 'L021',
    campaignId: '1',
    campaignName: 'Enterprise IT Security Campaign Q1 2026',
    firstName: 'Peter',
    lastName: 'Johnson',
    title: 'VP Technology',
    company: 'Education Technology Group',
    industry: 'Education',
    email: 'p.johnson@edtechgroup.com',
    phone: '+1 512-555-3456',
    country: 'United States',
    employeeSize: '500-1000',
    revenue: '$120M',
    leadScore: 79,
    status: 'Pending Review',
    deliveryDate: '2026-02-24',
  },
  {
    id: 'L022',
    campaignId: '3',
    campaignName: 'Financial Services BANT Qualification',
    firstName: 'Alexandra',
    lastName: 'Meyer',
    title: 'CFO',
    company: 'Swiss Capital Management',
    industry: 'Financial Services',
    email: 'a.meyer@swisscapital.ch',
    phone: '+41 22 555 7890',
    country: 'Switzerland',
    employeeSize: '500-1000',
    revenue: '$420M',
    leadScore: 87,
    status: 'Accepted',
    deliveryDate: '2026-02-17',
  },
  {
    id: 'L023',
    campaignId: '1',
    campaignName: 'Enterprise IT Security Campaign Q1 2026',
    firstName: 'Steven',
    lastName: 'Wright',
    title: 'Cybersecurity Lead',
    company: 'Aerospace Solutions',
    industry: 'Aerospace',
    email: 's.wright@aerosolutions.com',
    phone: '+1 253-555-4567',
    country: 'United States',
    employeeSize: '1000-2000',
    revenue: '$650M',
    leadScore: 85,
    status: 'Contacted',
    deliveryDate: '2026-02-21',
  },
  {
    id: 'L024',
    campaignId: '2',
    campaignName: 'Healthcare Content Syndication - Feb 2026',
    firstName: 'Victoria',
    lastName: 'Anderson',
    title: 'VP Healthcare Operations',
    company: 'National Care Network',
    industry: 'Healthcare',
    email: 'v.anderson@nationalcare.com',
    phone: '+1 617-555-8901',
    country: 'United States',
    employeeSize: '2000+',
    revenue: '$720M',
    leadScore: 92,
    status: 'Accepted',
    deliveryDate: '2026-02-08',
  },
  {
    id: 'L025',
    campaignId: '1',
    campaignName: 'Enterprise IT Security Campaign Q1 2026',
    firstName: 'Gregory',
    lastName: 'Mitchell',
    title: 'Director of IT',
    company: 'Automotive Manufacturing Co',
    industry: 'Automotive',
    email: 'g.mitchell@automfg.com',
    phone: '+1 313-555-2345',
    country: 'United States',
    employeeSize: '2000+',
    revenue: '$1.5B',
    leadScore: 88,
    status: 'Accepted',
    deliveryDate: '2026-02-16',
  },
  {
    id: 'L026',
    campaignId: '1',
    campaignName: 'Enterprise IT Security Campaign Q1 2026',
    firstName: 'Nicole',
    lastName: 'Turner',
    title: 'Security Architect',
    company: 'Media & Entertainment Group',
    industry: 'Media',
    email: 'n.turner@mediagroup.com',
    phone: '+1 818-555-6789',
    country: 'United States',
    employeeSize: '1000-2000',
    revenue: '$380M',
    leadScore: 81,
    status: 'Pending Review',
    deliveryDate: '2026-02-25',
  },
  {
    id: 'L027',
    campaignId: '3',
    campaignName: 'Financial Services BANT Qualification',
    firstName: 'Andrew',
    lastName: 'Davies',
    title: 'Head of Digital Transformation',
    company: 'UK Investment Bank',
    industry: 'Banking',
    email: 'a.davies@ukinvestment.co.uk',
    phone: '+44 20 7555 3456',
    country: 'United Kingdom',
    employeeSize: '2000+',
    revenue: '$1.1B',
    leadScore: 93,
    status: 'Accepted',
    deliveryDate: '2026-02-14',
  },
  {
    id: 'L028',
    campaignId: '1',
    campaignName: 'Enterprise IT Security Campaign Q1 2026',
    firstName: 'Jessica',
    lastName: 'Parker',
    title: 'IT Operations Manager',
    company: 'Hospitality Services Inc',
    industry: 'Hospitality',
    email: 'j.parker@hospitalityservices.com',
    phone: '+1 702-555-7890',
    country: 'United States',
    employeeSize: '500-1000',
    revenue: '$160M',
    leadScore: 74,
    status: 'Contacted',
    deliveryDate: '2026-02-23',
  },
  {
    id: 'L029',
    campaignId: '2',
    campaignName: 'Healthcare Content Syndication - Feb 2026',
    firstName: 'Timothy',
    lastName: 'Evans',
    title: 'Medical Technology Director',
    company: 'Diagnostic Solutions Ltd',
    industry: 'Healthcare',
    email: 't.evans@diagnostics.com',
    phone: '+1 919-555-4567',
    country: 'United States',
    employeeSize: '1000+',
    revenue: '$490M',
    leadScore: 88,
    status: 'Accepted',
    deliveryDate: '2026-02-10',
  },
  {
    id: 'L030',
    campaignId: '1',
    campaignName: 'Enterprise IT Security Campaign Q1 2026',
    firstName: 'Rebecca',
    lastName: 'Collins',
    title: 'Chief Information Officer',
    company: 'Professional Services Group',
    industry: 'Professional Services',
    email: 'r.collins@proservices.com',
    phone: '+1 404-555-8901',
    country: 'United States',
    employeeSize: '1000-2000',
    revenue: '$310M',
    leadScore: 89,
    status: 'Accepted',
    deliveryDate: '2026-02-15',
  },
  {
    id: 'L031',
    campaignId: '1',
    campaignName: 'Enterprise IT Security Campaign Q1 2026',
    firstName: 'Matthew',
    lastName: 'Harris',
    title: 'Information Security Director',
    company: 'Government Contractors Inc',
    industry: 'Government',
    email: 'm.harris@govcontractors.com',
    phone: '+1 703-555-2345',
    country: 'United States',
    employeeSize: '2000+',
    revenue: '$950M',
    leadScore: 91,
    status: 'Accepted',
    deliveryDate: '2026-02-13',
  },
  {
    id: 'L032',
    campaignId: '3',
    campaignName: 'Financial Services BANT Qualification',
    firstName: 'Catherine',
    lastName: 'Bernard',
    title: 'Innovation Director',
    company: 'European FinTech',
    industry: 'Financial Services',
    email: 'c.bernard@eufintech.eu',
    phone: '+32 2 555 6789',
    country: 'Belgium',
    employeeSize: '500-1000',
    revenue: '$230M',
    leadScore: 83,
    status: 'Contacted',
    deliveryDate: '2026-02-20',
  },
  {
    id: 'L033',
    campaignId: '1',
    campaignName: 'Enterprise IT Security Campaign Q1 2026',
    firstName: 'Richard',
    lastName: 'Phillips',
    title: 'Technology Security Manager',
    company: 'Transportation Systems',
    industry: 'Transportation',
    email: 'r.phillips@transportsystems.com',
    phone: '+1 206-555-3456',
    country: 'United States',
    employeeSize: '500-1000',
    revenue: '$175M',
    leadScore: 77,
    status: 'Pending Review',
    deliveryDate: '2026-02-24',
  },
  {
    id: 'L034',
    campaignId: '2',
    campaignName: 'Healthcare Content Syndication - Feb 2026',
    firstName: 'Amanda',
    lastName: 'Roberts',
    title: 'Healthcare IT Manager',
    company: 'Medical Research Foundation',
    industry: 'Healthcare',
    email: 'a.roberts@medresearch.org',
    phone: '+1 443-555-7890',
    country: 'United States',
    employeeSize: '1000+',
    revenue: '$360M',
    leadScore: 86,
    status: 'Accepted',
    deliveryDate: '2026-02-11',
  },
  {
    id: 'L035',
    campaignId: '1',
    campaignName: 'Enterprise IT Security Campaign Q1 2026',
    firstName: 'Joshua',
    lastName: 'Campbell',
    title: 'VP Cybersecurity',
    company: 'Real Estate Investment Trust',
    industry: 'Real Estate',
    email: 'j.campbell@reit.com',
    phone: '+1 214-555-4567',
    country: 'United States',
    employeeSize: '1000-2000',
    revenue: '$580M',
    leadScore: 84,
    status: 'Contacted',
    deliveryDate: '2026-02-22',
  },
  {
    id: 'L036',
    campaignId: '1',
    campaignName: 'Enterprise IT Security Campaign Q1 2026',
    firstName: 'Lauren',
    lastName: 'Stewart',
    title: 'IT Infrastructure Director',
    company: 'Chemical Manufacturing Corp',
    industry: 'Manufacturing',
    email: 'l.stewart@chemmfg.com',
    phone: '+1 832-555-8901',
    country: 'United States',
    employeeSize: '1000-2000',
    revenue: '$420M',
    leadScore: 80,
    status: 'Pending Review',
    deliveryDate: '2026-02-25',
  },
  {
    id: 'L037',
    campaignId: '3',
    campaignName: 'Financial Services BANT Qualification',
    firstName: 'Marcus',
    lastName: 'Weber',
    title: 'CFO',
    company: 'Munich Financial Group',
    industry: 'Banking',
    email: 'm.weber@munichfinancial.de',
    phone: '+49 89 555 2345',
    country: 'Germany',
    employeeSize: '2000+',
    revenue: '$780M',
    leadScore: 90,
    status: 'Accepted',
    deliveryDate: '2026-02-16',
  },
  {
    id: 'L038',
    campaignId: '1',
    campaignName: 'Enterprise IT Security Campaign Q1 2026',
    firstName: 'Stephanie',
    lastName: 'Morgan',
    title: 'Security Operations Manager',
    company: 'Utility Services Company',
    industry: 'Utilities',
    email: 's.morgan@utilityservices.com',
    phone: '+1 404-555-6789',
    country: 'United States',
    employeeSize: '2000+',
    revenue: '$1.3B',
    leadScore: 87,
    status: 'Accepted',
    deliveryDate: '2026-02-17',
  },
  {
    id: 'L039',
    campaignId: '2',
    campaignName: 'Healthcare Content Syndication - Feb 2026',
    firstName: 'Benjamin',
    lastName: 'Reed',
    title: 'Clinical Operations Director',
    company: 'Integrated Health Systems',
    industry: 'Healthcare',
    email: 'b.reed@integratedhealth.com',
    phone: '+1 216-555-3456',
    country: 'United States',
    employeeSize: '2000+',
    revenue: '$620M',
    leadScore: 91,
    status: 'Accepted',
    deliveryDate: '2026-02-09',
  },
  {
    id: 'L040',
    campaignId: '1',
    campaignName: 'Enterprise IT Security Campaign Q1 2026',
    firstName: 'Emily',
    lastName: 'Brooks',
    title: 'IT Compliance Officer',
    company: 'Retail Banking Corporation',
    industry: 'Banking',
    email: 'e.brooks@retailbanking.com',
    phone: '+1 704-555-7890',
    country: 'United States',
    employeeSize: '1000-2000',
    revenue: '$440M',
    leadScore: 82,
    status: 'Contacted',
    deliveryDate: '2026-02-21',
  },
  {
    id: 'L041',
    campaignId: '1',
    campaignName: 'Enterprise IT Security Campaign Q1 2026',
    firstName: 'Anthony',
    lastName: 'Bell',
    title: 'Director of Information Security',
    company: 'Construction Engineering Ltd',
    industry: 'Construction',
    email: 'a.bell@constengineering.com',
    phone: '+1 713-555-4567',
    country: 'United States',
    employeeSize: '500-1000',
    revenue: '$195M',
    leadScore: 75,
    status: 'Pending Review',
    deliveryDate: '2026-02-26',
  },
  {
    id: 'L042',
    campaignId: '3',
    campaignName: 'Financial Services BANT Qualification',
    firstName: 'Natalie',
    lastName: 'Wilson',
    title: 'Head of Digital Banking',
    company: 'Canadian Bank Corporation',
    industry: 'Banking',
    email: 'n.wilson@canadianbank.ca',
    phone: '+1 416-555-8901',
    country: 'Canada',
    employeeSize: '2000+',
    revenue: '$1.4B',
    leadScore: 94,
    status: 'Accepted',
    deliveryDate: '2026-02-12',
  },
  {
    id: 'L043',
    campaignId: '1',
    campaignName: 'Enterprise IT Security Campaign Q1 2026',
    firstName: 'Jeffrey',
    lastName: 'Gray',
    title: 'CTO',
    company: 'Software Development Co',
    industry: 'Technology',
    email: 'j.gray@softwaredev.com',
    phone: '+1 415-555-2345',
    country: 'United States',
    employeeSize: '500-1000',
    revenue: '$145M',
    leadScore: 79,
    status: 'Contacted',
    deliveryDate: '2026-02-23',
  },
  {
    id: 'L044',
    campaignId: '2',
    campaignName: 'Healthcare Content Syndication - Feb 2026',
    firstName: 'Melissa',
    lastName: 'Powell',
    title: 'VP Medical Technology',
    company: 'Biotech Research Corp',
    industry: 'Healthcare',
    email: 'm.powell@biotechresearch.com',
    phone: '+1 858-555-6789',
    country: 'United States',
    employeeSize: '1000+',
    revenue: '$520M',
    leadScore: 89,
    status: 'Accepted',
    deliveryDate: '2026-02-10',
  },
  {
    id: 'L045',
    campaignId: '1',
    campaignName: 'Enterprise IT Security Campaign Q1 2026',
    firstName: 'Patrick',
    lastName: 'Russell',
    title: 'Security Operations Director',
    company: 'Financial Technology Partners',
    industry: 'Financial Services',
    email: 'p.russell@fintechpartners.com',
    phone: '+1 212-555-3456',
    country: 'United States',
    employeeSize: '1000-2000',
    revenue: '$370M',
    leadScore: 86,
    status: 'Accepted',
    deliveryDate: '2026-02-18',
  },
  {
    id: 'L046',
    campaignId: '1',
    campaignName: 'Enterprise IT Security Campaign Q1 2026',
    firstName: 'Kimberly',
    lastName: 'Henderson',
    title: 'IT Security Specialist',
    company: 'Publishing Group International',
    industry: 'Media',
    email: 'k.henderson@publishinggroup.com',
    phone: '+1 212-555-7890',
    country: 'United States',
    employeeSize: '500-1000',
    revenue: '$125M',
    leadScore: 71,
    status: 'Pending Review',
    deliveryDate: '2026-02-26',
  },
  {
    id: 'L047',
    campaignId: '3',
    campaignName: 'Financial Services BANT Qualification',
    firstName: 'Vincent',
    lastName: 'Dubois',
    title: 'Innovation Director',
    company: 'Luxembourg Investment Bank',
    industry: 'Banking',
    email: 'v.dubois@luxinvestment.lu',
    phone: '+352 27 555 4567',
    country: 'Luxembourg',
    employeeSize: '500-1000',
    revenue: '$340M',
    leadScore: 85,
    status: 'Contacted',
    deliveryDate: '2026-02-19',
  },
  {
    id: 'L048',
    campaignId: '1',
    campaignName: 'Enterprise IT Security Campaign Q1 2026',
    firstName: 'Caroline',
    lastName: 'Jenkins',
    title: 'Chief Security Officer',
    company: 'E-commerce Solutions Inc',
    industry: 'Technology',
    email: 'c.jenkins@ecommercesolutions.com',
    phone: '+1 512-555-8901',
    country: 'United States',
    employeeSize: '1000-2000',
    revenue: '$290M',
    leadScore: 88,
    status: 'Accepted',
    deliveryDate: '2026-02-15',
  },
  {
    id: 'L049',
    campaignId: '2',
    campaignName: 'Healthcare Content Syndication - Feb 2026',
    firstName: 'George',
    lastName: 'Murphy',
    title: 'Healthcare Technology Manager',
    company: 'Community Health Network',
    industry: 'Healthcare',
    email: 'g.murphy@communityhealth.com',
    phone: '+1 317-555-2345',
    country: 'United States',
    employeeSize: '1000+',
    revenue: '$395M',
    leadScore: 87,
    status: 'Accepted',
    deliveryDate: '2026-02-11',
  },
  {
    id: 'L050',
    campaignId: '1',
    campaignName: 'Enterprise IT Security Campaign Q1 2026',
    firstName: 'Diana',
    lastName: 'Sanders',
    title: 'VP Information Technology',
    company: 'Agricultural Technologies Co',
    industry: 'Agriculture',
    email: 'd.sanders@agritech.com',
    phone: '+1 515-555-6789',
    country: 'United States',
    employeeSize: '500-1000',
    revenue: '$165M',
    leadScore: 73,
    status: 'Pending Review',
    deliveryDate: '2026-02-27',
  },
];

// ============ MESSAGES ============
export interface Message {
  id: string;
  from: string;
  fromRole: 'client' | 'datamatics';
  subject: string;
  content: string;
  timestamp: string;
  read: boolean;
  campaignId?: string;
  attachments?: { name: string; size: string }[];
}

export const mockMessages: Message[] = [
  {
    id: 'M001',
    from: 'Sarah Johnson',
    fromRole: 'datamatics',
    subject: 'Campaign Update: Milestone Reached',
    content: 'Hi John, I wanted to let you know that we\'ve reached the 50% milestone on your Enterprise IT Security campaign. We\'re on track for delivery and the lead quality has been excellent. Let me know if you have any questions!',
    timestamp: '2026-02-27T10:30:00',
    read: false,
    campaignId: '1',
  },
  {
    id: 'M002',
    from: 'John Smith',
    fromRole: 'client',
    subject: 'RE: Lead Quality Question',
    content: 'Thanks for the quick response. The leads have been great so far. Can we schedule a call to discuss expanding this campaign?',
    timestamp: '2026-02-26T15:45:00',
    read: true,
    campaignId: '1',
  },
  {
    id: 'M003',
    from: 'David Park',
    fromRole: 'datamatics',
    subject: 'Invoice INV-2026-001298 Available',
    content: 'Your invoice for February is now available. You can view and download it from your Invoices page.',
    timestamp: '2026-02-25T09:00:00',
    read: true,
  },
  {
    id: 'M004',
    from: 'Sarah Johnson',
    fromRole: 'datamatics',
    subject: 'Weekly Performance Report - Week of Feb 20',
    content: 'Please find attached your weekly performance report. This week we delivered 52 leads with a 91% acceptance rate. Great results!',
    timestamp: '2026-02-24T14:20:00',
    read: true,
    campaignId: '1',
    attachments: [{ name: 'Weekly_Report_Feb20.pdf', size: '245 KB' }],
  },
];

// ============ DOCUMENTS ============
export interface Document {
  id: string;
  name: string;
  type: 'contract' | 'report' | 'invoice' | 'brief' | 'other';
  size: string;
  uploadDate: string;
  uploadedBy: string;
  campaignId?: string;
  campaignName?: string;
}

export const mockDocuments: Document[] = [
  {
    id: 'D001',
    name: 'Master Service Agreement - TechVentures',
    type: 'contract',
    size: '1.2 MB',
    uploadDate: '2026-01-10',
    uploadedBy: 'Sarah Johnson',
  },
  {
    id: 'D002',
    name: 'Job Card - Enterprise IT Security Q1',
    type: 'contract',
    size: '450 KB',
    uploadDate: '2026-01-12',
    uploadedBy: 'John Smith',
    campaignId: '1',
    campaignName: 'Enterprise IT Security Campaign Q1 2026',
  },
  {
    id: 'D003',
    name: 'Campaign Brief - IT Security',
    type: 'brief',
    size: '680 KB',
    uploadDate: '2026-01-08',
    uploadedBy: 'John Smith',
    campaignId: '1',
    campaignName: 'Enterprise IT Security Campaign Q1 2026',
  },
  {
    id: 'D004',
    name: 'Weekly Report - Feb 24',
    type: 'report',
    size: '245 KB',
    uploadDate: '2026-02-24',
    uploadedBy: 'Sarah Johnson',
    campaignId: '1',
    campaignName: 'Enterprise IT Security Campaign Q1 2026',
  },
  {
    id: 'D005',
    name: 'Invoice - INV-2026-001234',
    type: 'invoice',
    size: '180 KB',
    uploadDate: '2026-02-28',
    uploadedBy: 'System',
    campaignId: '2',
    campaignName: 'Healthcare Content Syndication - Feb 2026',
  },
];

// ============ NOTIFICATIONS ============
export interface Notification {
  id: string;
  type: 'success' | 'warning' | 'info' | 'error';
  title: string;
  message: string;
  timestamp: string;
  read: boolean;
  actionUrl?: string;
}

export const mockNotifications: Notification[] = [
  {
    id: 'N001',
    type: 'success',
    title: 'New leads delivered',
    message: '52 new leads delivered for Enterprise IT Security Campaign',
    timestamp: '2026-02-27T09:15:00',
    read: false,
    actionUrl: '/campaigns/1',
  },
  {
    id: 'N002',
    type: 'info',
    title: 'Invoice ready',
    message: 'Invoice INV-2026-001298 is now available',
    timestamp: '2026-02-26T10:00:00',
    read: false,
    actionUrl: '/invoices',
  },
  {
    id: 'N003',
    type: 'warning',
    title: 'Campaign pacing slower than expected',
    message: 'SaaS Appointment Setting campaign is 25% behind target',
    timestamp: '2026-02-25T14:30:00',
    read: true,
    actionUrl: '/campaigns/4',
  },
  {
    id: 'N004',
    type: 'success',
    title: 'Campaign completed',
    message: 'Healthcare Content Syndication campaign completed successfully',
    timestamp: '2026-02-28T16:00:00',
    read: true,
    actionUrl: '/campaigns/2',
  },
];

// ============ TEAM MEMBERS ============
export interface TeamMember {
  id: string;
  name: string;
  email: string;
  role: 'Admin' | 'Manager' | 'Viewer';
  avatar?: string;
  status: 'Active' | 'Invited';
  joinedDate: string;
  lastActive: string;
}

export const mockTeamMembers: TeamMember[] = [
  {
    id: 'U001',
    name: 'John Smith',
    email: 'john.smith@techventures.com',
    role: 'Admin',
    status: 'Active',
    joinedDate: '2025-11-01',
    lastActive: '2026-02-27T10:45:00',
  },
  {
    id: 'U002',
    name: 'Emily Chen',
    email: 'emily.chen@techventures.com',
    role: 'Manager',
    status: 'Active',
    joinedDate: '2025-12-15',
    lastActive: '2026-02-27T09:20:00',
  },
  {
    id: 'U003',
    name: 'Michael Brown',
    email: 'michael.brown@techventures.com',
    role: 'Viewer',
    status: 'Active',
    joinedDate: '2026-01-10',
    lastActive: '2026-02-26T16:30:00',
  },
  {
    id: 'U004',
    name: 'Sarah Williams',
    email: 'sarah.williams@techventures.com',
    role: 'Viewer',
    status: 'Invited',
    joinedDate: '2026-02-25',
    lastActive: '',
  },
];

// ============ ANALYTICS DATA ============
export interface AnalyticsData {
  monthlyLeads: { month: string; delivered: number; accepted: number; target: number }[];
  campaignPerformance: { campaign: string; leads: number; acceptance: number; revenue: number }[];
  industryBreakdown: { industry: string; count: number; percentage: number }[];
  conversionFunnel: { stage: string; count: number; percentage: number }[];
}

export const mockAnalytics: AnalyticsData = {
  monthlyLeads: [
    { month: 'Oct 2025', delivered: 450, accepted: 420, target: 500 },
    { month: 'Nov 2025', delivered: 520, accepted: 485, target: 550 },
    { month: 'Dec 2025', delivered: 380, accepted: 360, target: 400 },
    { month: 'Jan 2026', delivered: 610, accepted: 575, target: 600 },
    { month: 'Feb 2026', delivered: 680, accepted: 640, target: 650 },
  ],
  campaignPerformance: [
    { campaign: 'Enterprise IT Security', leads: 320, acceptance: 89, revenue: 14400 },
    { campaign: 'Healthcare Content Syndication', leads: 850, acceptance: 96, revenue: 29750 },
    { campaign: 'Financial Services BANT', leads: 65, acceptance: 89, revenue: 7800 },
    { campaign: 'SaaS Appointments', leads: 18, acceptance: 89, revenue: 3600 },
  ],
  industryBreakdown: [
    { industry: 'Information Technology', count: 450, percentage: 35 },
    { industry: 'Healthcare', count: 380, percentage: 30 },
    { industry: 'Financial Services', count: 250, percentage: 20 },
    { industry: 'Manufacturing', count: 120, percentage: 10 },
    { industry: 'Retail', count: 65, percentage: 5 },
  ],
  conversionFunnel: [
    { stage: 'Sourced', count: 1500, percentage: 100 },
    { stage: 'Validated', count: 1280, percentage: 85 },
    { stage: 'Delivered', count: 1200, percentage: 80 },
    { stage: 'Accepted', count: 1080, percentage: 72 },
    { stage: 'Contacted', count: 650, percentage: 43 },
  ],
};