/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "hpugrvwimclohhvwuwox"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhwdWdydndpbWNsb2hodnd1d294Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIyNTQ2MDEsImV4cCI6MjA4NzgzMDYwMX0.XXlHk8gbg77IwWdU-di-yZJd-W1Rkb7_VLrACHikK70"